import {servicePrice} from "../../lib/regional-pricing";
import Link from "next/link";
import NewCustomerLeadForm from "../../components/NewCustomerLeadForm";
import PublicPage from "../../components/PublicPage";
export const metadata={title:"Yeni Müşteri | AI Visibility",description:"AI Visibility ön değerlendirme ve müşteri başvuru süreci."};
const allowed=new Set(["business-diagnosis","business-solution","business-monitoring"]);
export default async function NewCustomerPage({searchParams}){
  const p=await searchParams;const service=allowed.has(String(p?.service||""))?String(p.service):"";const country=String(p?.country||"").slice(0,120);
  const en=country&&!/^(Türkiye|Turkey|TR)$/i.test(country);const language=en?"en":"tr";
  const prices=Object.fromEntries([["TRY","Türkiye"],["EUR","Germany"],["GBP","United Kingdom"],["USD","United States"]].map(([currency,country])=>[currency,[...allowed].map(service=>servicePrice({service,country,language}))]));
  const steps=en?["Share your business and service details.","We review fit, scope and available delivery path.","Final scope, total price and legal terms are confirmed before payment.","If an active payment method is available, payment is completed and verified.","Your account activation and access steps are completed.","You sign in to the customer portal and follow the service process."]:["İşletme ve hizmet bilgilerinizi gönderin.","Uygunluk, kapsam ve mevcut hizmet akışı değerlendirilir.","Ödeme öncesinde kesin kapsam, toplam ücret ve yasal koşullar doğrulanır.","Aktif ödeme yöntemi mevcutsa ödeme tamamlanır ve doğrulanır.","Hesap aktivasyonu ve erişim adımları tamamlanır.","Müşteri paneline girerek hizmet sürecini takip edersiniz."];
  return <PublicPage title={en?"Start your AI visibility review":"AI görünürlük ön değerlendirmenizi başlatın"} subtitle={en?"A clear onboarding flow from business context to verified scope and customer access.":"İşletme bilgilerinden doğrulanmış hizmet kapsamına ve müşteri erişimine uzanan şeffaf bir başlangıç akışı."}>
    <section className="customer-onboarding-intro"><div><span className="public-kicker">{en?"ONBOARDING":"BAŞLANGIÇ AKIŞI"}</span><h2>{en?"No hidden scope. No surprise pricing.":"Gizli kapsam yok. Sürpriz ücret yok."}</h2><p>{en?"Your selected service, market, scope and total price are reviewed before any payment step.":"Seçtiğiniz hizmet, ülke, kapsam ve toplam ücret herhangi bir ödeme adımından önce gözden geçirilir."}</p></div><div className="onboarding-trust"><span>✓ {en?"Service scope confirmed":"Hizmet kapsamı doğrulanır"}</span><span>✓ {en?"Total price shown before payment":"Toplam ücret ödeme öncesinde gösterilir"}</span><span>✓ {en?"Legal terms remain accessible":"Yasal koşullar erişilebilir kalır"}</span></div></section>
    <NewCustomerLeadForm initialService={service} initialCountry={country} initialLanguage={language} prices={prices}/>
    <section className="onboarding-steps"><span className="public-kicker">{en?"HOW IT WORKS":"NASIL ÇALIŞIR"}</span><h2>{en?"A transparent path from application to delivery":"Başvurudan hizmete şeffaf ilerleyiş"}</h2><div>{steps.map((step,i)=><article key={step}><span>0{i+1}</span><p>{step}</p></article>)}</div></section>
    <section className="public-cta-band"><div><h2>{en?"Already have an account?":"Zaten hesabınız var mı?"}</h2><p>{en?"Use your verified email and password to access the customer portal.":"Doğrulanmış e-posta ve şifrenizle müşteri paneline giriş yapabilirsiniz."}</p></div><div><Link className="public-primary-link" href="/musteri-giris">{en?"Customer sign in →":"Müşteri girişi →"}</Link><Link className="public-secondary-link" href="/iletisim">{en?"Support →":"Destek →"}</Link></div></section>
  </PublicPage>;
}
