"use client";
import {useState} from "react";
import "./preview.css";
const copy={
 tr:{
  nav:["Platform","Çözümler","Örnek rapor","Güven"],login:"Müşteri girişi",eyebrow:"DIGITAL VISIBILITY INTELLIGENCE",headline:"Yapay zekâda görünür olmak yetmez. Neden görünür olduğunuzu da bilin.",subtitle:"AI Visibility; markanızın yapay zekâ aramalarındaki görünürlüğünü ölçer, bulguları kaynaklarıyla açıklar, sorunları önceliklendirir ve iyileştirme sürecini tek yerde takip etmenizi sağlar.",cta:"Platformu keşfet",secondary:"Örnek raporu incele",proof:"Kanıta dayalı analiz · Şeffaf metodoloji · TR / EN deneyim",platformTitle:"Görünürlükten aksiyona tek platform",platformLead:"Sadece bir skor vermek yerine neyin çalıştığını, neyin eksik olduğunu ve sıradaki en değerli adımı gösteren çalışma akışı.",pillars:["Keşfet","Kanıtla","Önceliklendir","İyileştir"],pillarText:["AI aramalarında marka, konu ve kaynak sinyallerini tarayın.","Her önemli bulguyu kaynak ve ölçüm bağlamıyla ilişkilendirin.","Sorunları iş etkisi ve güven düzeyine göre sıralayın.","Onaylanan geliştirmeleri uygulayın, yeniden ölçün ve değişimi takip edin."],outcomesTitle:"Yönetici için netlik. Ekip için yapılacak iş.",outcomes:["Görünürlük durumunu tek ekranda anlayın","Hangi kaynakların markanızı desteklediğini görün","Eksikleri önem sırasına göre yönetin","Tekrarlanan ölçümlerle gelişimi izleyin"],solutions:"İşletmenize göre kullanım alanları",sectors:["Üretim ve ihracat","Uzman B2B hizmetler","E-ticaret ve ürün markaları","Dijital ajanslar"],report:"Karar vermeyi kolaylaştıran rapor",demo:"Temsili örnek — gerçek müşteri verisi değildir",metric:"AI görünürlük değerlendirmesi",note:"Puanlar yalnızca doğrulanmış ölçüm yapıldığında hesaplanır. Belirli sıralama, satış veya gelir sonucu garanti edilmez.",contact:"AI görünürlüğünüzü daha sistemli yönetin",contactText:"Hizmet kapsamını, ülkeye göre fiyatlandırmayı ve çalışma yöntemimizi inceleyin. Doğrulanmış iletişim bilgileri iletişim sayfamızda yayımlanır.",footer:"Şeffaf ölçüm. Kanıta dayalı öneriler. Uygulanabilir aksiyon.",trust:"Kurumsal güveni tasarımın parçası değil, ürünün temeli yapıyoruz",trustItems:["Bulgular kaynak bağlantıları ve ölçüm bağlamıyla sunulur","Temsili raporlar ve demo veriler açıkça etiketlenir","Sonuç, sıralama veya gelir garantisi verilmez","Müşteri ve yönetici alanları birbirinden ayrılır","Gizlilik, KVKK, sözleşme ve iade koşulları erişilebilirdir","Yalnızca doğrulanmış özellikler müşteri karşısında aktif gösterilir"],legal:"Yasal bilgiler",privacy:"Gizlilik",kvkk:"KVKK",terms:"Hizmet sözleşmesi",refund:"İptal ve iade",contactLink:"İletişim",contactCta:"İletişim bilgileri",pricing:"Hizmetler ve fiyatlar"
 },
 en:{
  nav:["Platform","Solutions","Sample report","Trust"],login:"Client sign in",eyebrow:"DIGITAL VISIBILITY INTELLIGENCE",headline:"Visibility in AI is not enough. Know why you are visible.",subtitle:"AI Visibility measures how your brand appears in AI search, explains findings with evidence, prioritizes gaps, and helps you track improvement in one place.",cta:"Explore the platform",secondary:"View sample report",proof:"Evidence-led analysis · Transparent methodology · TR / EN experience",platformTitle:"From visibility to action in one platform",platformLead:"Instead of giving you only a score, the workflow shows what works, what is missing, and the next most valuable action.",pillars:["Discover","Evidence","Prioritize","Improve"],pillarText:["Review brand, topic, and source signals across AI search experiences.","Connect important findings to sources and measurement context.","Rank issues by business relevance and confidence.","Apply approved improvements, remeasure, and track change."],outcomesTitle:"Clarity for leaders. Action for teams.",outcomes:["Understand visibility status at a glance","See which sources support your brand presence","Manage gaps by priority","Track progress through repeat measurements"],solutions:"Use cases built around your business",sectors:["Manufacturing & export","Specialist B2B services","E-commerce & product brands","Digital agencies"],report:"A report designed for decisions",demo:"Illustrative demo — not real customer data",metric:"AI visibility assessment",note:"Scores require verified measurements. No ranking, sales, or revenue outcome is guaranteed.",contact:"Manage AI visibility with more discipline",contactText:"Explore service scope, regional pricing, and our working method. Verified contact details are published on our contact page.",footer:"Transparent measurement. Evidence-based recommendations. Actionable next steps.",trust:"Trust is not a visual layer. It is part of the product.",trustItems:["Findings include source links and measurement context","Illustrative reports and demo data are clearly labeled","No ranking, revenue, or outcome guarantees","Customer and administrator areas remain separated","Privacy, legal terms, and cancellation policies remain accessible","Only verified capabilities are presented as active"],legal:"Legal information",privacy:"Privacy",kvkk:"Data protection",terms:"Service agreement",refund:"Cancellation and refunds",contactLink:"Contact",contactCta:"Contact details",pricing:"Services and pricing"
 }
};
const reportBars=[72,58,84];
export default function Home(){const [lang,setLang]=useState("tr");const t=copy[lang];return <div className="site-preview"><main>
<header className="nav wrap"><a href="#top" className="brand"><span className="mark">◈</span><span>AI Visibility</span></a><nav aria-label="Main navigation"><a href="#platform">{t.nav[0]}</a><a href="#solutions">{t.nav[1]}</a><a href="#report">{t.nav[2]}</a><a href="#trust">{t.nav[3]}</a></nav><div className="nav-actions"><button className="language" onClick={()=>setLang(lang==="tr"?"en":"tr")} aria-label="Change language">{lang==="tr"?"EN":"TR"}</button><a className="login" href="/musteri-giris">{t.login}</a></div></header>
<section id="top" className="hero wrap"><div className="hero-content"><p className="eyebrow"><span className="dot"/> {t.eyebrow}</p><h1>{t.headline}</h1><p className="lead">{t.subtitle}</p><div className="actions"><a className="btn primary" href="#platform">{t.cta} <span aria-hidden>↗</span></a><a className="btn ghost" href="#report">{t.secondary}</a></div><p className="proof-line">{t.proof}</p><p className="disclaimer">{t.note}</p></div><div className="visual enterprise-visual" aria-label={t.demo}><div className="visual-top"><span>AI Visibility / Executive View</span><span className="demo-tag">DEMO</span></div><div className="visual-body"><div className="hero-score"><div className="score-orb"><strong>72</strong><span>/100</span></div><div><span className="micro">{t.metric}</span><strong className="hero-status">Evidence-backed</strong><small>Source-linked findings</small></div></div><div className="mini-grid"><div><span>Discovery</span><b>12</b><small>signals reviewed</small></div><div><span>Evidence</span><b>8</b><small>linked findings</small></div><div><span>Priority</span><b>3</b><small>next actions</small></div></div><div className="bars">{[68,81,54,76].map((w,i)=><div key={i} className="bar-track"><div style={{width:w+"%"}}/></div>)}</div><p className="sample-label">{t.demo}</p></div></div></section>
<section id="platform" className="section wrap platform-section"><div className="section-heading"><p className="eyebrow">01 / PLATFORM</p><h2>{t.platformTitle}</h2><p>{t.platformLead}</p></div><div className="platform-grid">{t.pillars.map((s,i)=><article className="platform-card" key={s}><span className="number">0{i+1}</span><div className="platform-icon" aria-hidden>{["⌕","◎","↟","↻"][i]}</div><h3>{s}</h3><p>{t.pillarText[i]}</p></article>)}</div></section>
<section className="section wrap outcome-section"><div className="outcome-copy"><p className="eyebrow">02 / OUTCOMES</p><h2>{t.outcomesTitle}</h2></div><div className="outcome-list">{t.outcomes.map((item,i)=><div key={item}><span>0{i+1}</span><p>{item}</p></div>)}</div></section>
<section id="solutions" className="section wrap"><p className="eyebrow">03 / SOLUTIONS</p><h2>{t.solutions}</h2><div className="sectors">{t.sectors.map((s,i)=><a href="/hizmetler" className="sector" key={s}><span>0{i+1}</span><strong>{s}</strong><span aria-hidden>↗</span></a>)}</div></section>
<section id="report" className="section wrap report-section"><div className="report-copy"><p className="eyebrow">04 / INSIGHTS</p><h2>{t.report}</h2><p>{t.platformLead}</p><a className="text-cta" href="/hizmetler">{t.pricing} ↗</a></div><div className="report"><div className="report-head"><span className="demo-tag">DEMO</span><span className="report-date">AI Visibility / Report</span></div><h3>{t.metric}</h3><p>{t.demo}</p><div className="report-grid">{["Discovery","Evidence","Readiness"].map((label,i)=><div key={label}><span>{label}</span><strong>{reportBars[i]}%</strong><div className="meter"><i style={{width:reportBars[i]+"%"}}/></div></div>)}</div><div className="finding"><span>01</span><div><b>Priority finding</b><p>Evidence, context and next action are grouped together.</p></div></div><small>{t.note}</small></div></section>
<section id="trust" className="section wrap trust-section" aria-labelledby="trust-heading"><p className="eyebrow">05 / TRUST</p><h2 id="trust-heading">{t.trust}</h2><div className="trust-list">{t.trustItems.map(item=><div className="trust-item" key={item}><span aria-hidden="true">✓</span><p>{item}</p></div>)}</div></section>
<section id="contact" className="section wrap contact premium-contact"><div><p className="eyebrow">06 / NEXT STEP</p><h2>{t.contact}</h2><p>{t.contactText}</p></div><div className="contact-actions"><a className="btn primary" href="/hizmetler">{t.pricing} ↗</a><a className="btn ghost" href="/iletisim">{t.contactCta} ↗</a></div></section>
<footer className="wrap footer"><div className="footer-top"><strong>◈ AI Visibility</strong><span>{t.footer}</span></div><nav className="footer-links" aria-label={t.legal}><a href="/hizmetler">{t.pricing}</a><a href="/iletisim">{t.contactLink}</a><a href="/gizlilik">{t.privacy}</a><a href="/kvkk">{t.kvkk}</a><a href="/mesafeli-hizmet-sozlesmesi">{t.terms}</a><a href="/iptal-iade">{t.refund}</a></nav><small>© 2026 AI Visibility</small></footer>
</main></div>}
