import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {repeatEvidenceOptions} from '../lib/answer-evidence-comparison.js';
const source=(await readFile(new URL('../lib/answer-evidence-automation.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const {chooseAutomaticEvidence,runAutomaticAnswerEvidence}=new Function('repeatEvidenceOptions',source+';return {chooseAutomaticEvidence,runAutomaticAnswerEvidence};')(repeatEvidenceOptions);
const entity={id:'old',name:'Acme Precision',domain:'acme.com',sector:'machining',city:'Berlin'};
const result={queries:['Suggest machining providers in Berlin.'],observations:[{provider:'Perplexity',model:'fixture',mode:'agent-api',brandPrompted:false,truncated:false}],errors:[],summary:{neutralComplete:1}};
const run={id:'old-run',entityId:'old',entityType:'prospect',entityName:entity.name,domain:entity.domain,result};
const due=[{entity,run}],fresh=[{...entity,id:'new',name:'New Company',domain:'new.com'}],providers=['Perplexity'];
test('automatic capacity alternates first observations and overdue single-query repeats',()=>{assert.equal(chooseAutomaticEvidence({due,fresh,providers,slot:2}).kind,'first');const selected=chooseAutomaticEvidence({due,fresh,providers,slot:3});assert.equal(selected.kind,'repeat');assert.deepEqual(selected.options.queries,result.queries);assert.deepEqual(selected.options.providers,['Perplexity']);assert.equal(selected.options.automaticRepeat,true);assert.equal(chooseAutomaticEvidence({due,fresh:[],providers,slot:2}).kind,'repeat');assert.equal(chooseAutomaticEvidence({due:[],fresh,providers,slot:3}).kind,'first')});
test('changed identities, unavailable providers, prompted/partial and multi-call baselines cannot be scheduled',()=>{for(const modified of [{...run,entityName:'Changed'},{...run,result:{...result,queries:[...result.queries,'Another valid query?']}},{...run,result:{...result,observations:[{...result.observations[0],truncated:true}]}},{...run,result:{...result,observations:[{...result.observations[0],brandPrompted:true}]}}])assert.equal(chooseAutomaticEvidence({due:[{entity,run:modified}],providers,slot:3}),null);assert.equal(chooseAutomaticEvidence({due,providers:['Gemini'],slot:3}),null);assert.equal(chooseAutomaticEvidence({fresh:[{...entity,sector:''}],providers}),null)});
function fixture({available=true,fail=false,auditFail=false}={}){const state={claimed:false,calls:[],measured:[]};const pool={query:async(sql,p)=>{state.calls.push({sql,p});if(sql.includes('FROM (SELECT DISTINCT'))return {rows:[{...entity,runId:run.id,entityName:run.entityName,runDomain:run.domain,result,createdAt:'2026-10-06T10:00:00Z'}]};if(sql.includes('EXTRACT(EPOCH'))return {rows:[{hour:3}]};if(sql.startsWith('INSERT')){if(!available||state.claimed)return {rows:[]};state.claimed=true;return {rows:[{slot:'hour-3'}]}};if(sql.startsWith('UPDATE')&&auditFail)throw Error('audit-failed');return {rows:[]}}};const deps={clientPlans:async()=>[],pool,providers:()=>providers,guard:async()=>({mode:'normal'}),measure:async(e,o)=>{state.measured.push({e,o});if(fail)throw Error('provider-failed');return {id:'saved',result:{...result,comparison:{pairs:[{}]}}}}};return {state,deps}}
test('database hour claim allows only one automatic call across repeats and reruns',async()=>{const f=fixture();const first=await runAutomaticAnswerEvidence(fresh,f.deps);assert.equal(first.kind,'repeat');assert.equal(first.id,'saved');assert.equal(first.slotAuditSaved,true);assert.equal(f.state.measured.length,1);assert.equal(f.state.measured[0].o.repeatRunId,'old-run');const second=await runAutomaticAnswerEvidence(fresh,f.deps);assert.equal(second.skipped,'hourly-evidence-slot-used');assert.equal(f.state.measured.length,1);const sql=f.state.calls.find(x=>x.sql.includes('FROM (SELECT DISTINCT')).sql;assert.match(sql,/24 hours/);assert.match(sql,/NOT EXISTS\(SELECT 1 FROM answer_evidence_automation_slots/);assert.match(sql,/client_id IS NULL/);assert.match(sql,/LIMIT 20/)});
test('claimed failures consume the hour and saved evidence survives slot audit failure',async()=>{const f=fixture({fail:true});await assert.rejects(()=>runAutomaticAnswerEvidence([],f.deps));assert.ok(f.state.calls.some(x=>x.sql.includes("status='failed'")));assert.equal((await runAutomaticAnswerEvidence([],f.deps)).skipped,'hourly-evidence-slot-used');assert.equal(f.state.measured.length,1);const g=fixture({auditFail:true});const r=await runAutomaticAnswerEvidence([],g.deps);assert.equal(r.id,'saved');assert.equal(r.slotAuditSaved,false)});
test('emergency guard or missing providers cannot spend an automatic call',async()=>{const f=fixture();f.deps.guard=async()=>({mode:'emergency'});assert.equal((await runAutomaticAnswerEvidence([],f.deps)).skipped,'ai-budget-exhausted');assert.equal(f.state.calls.length,0);f.deps.guard=async()=>({mode:'normal'});f.deps.providers=()=>[];assert.equal((await runAutomaticAnswerEvidence([],f.deps)).skipped,'provider-unavailable');assert.equal(f.state.measured.length,0)});
test('customer followup shares the single hourly claim and gets a reserved turn without extra capacity',async()=>{const f=fixture();f.deps.clientPlans=async()=>[{entity:{id:'customer',entityType:'client',name:'Paid Customer'},kind:'repeat',options:{queries:['Suggest machining providers in Berlin.'],providers:['Perplexity'],automaticRepeat:true,implementationWorkId:'work'}}];const r=await runAutomaticAnswerEvidence(fresh,f.deps);assert.equal(r.entityType,'client');assert.equal(f.state.measured.length,1);assert.equal(f.state.measured[0].e.id,'customer');assert.equal(f.state.calls.find(x=>x.sql.startsWith('INSERT')).p[2],'client');assert.equal((await runAutomaticAnswerEvidence(fresh,f.deps)).skipped,'hourly-evidence-slot-used');assert.equal(f.state.measured.length,1)});
