import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {summarizeDailyAnswerEvidence} from '../lib/answer-evidence-daily-rules.js';
import {validReportDate,reportDay} from '../lib/reporting.js';
const observation={provider:'Gemini',model:'fixture',mode:'api-no-search',query:'Suggest machining companies in Berlin.',brandPrompted:false,truncated:false,brandMentioned:true,officialCitation:false};
const pair={...observation,previousRunId:'old',before:{brandMentioned:false},after:{brandMentioned:true}};
const run={id:'one',entityType:'prospect',entityId:'entity',entityName:'Acme Precision',createdAt:'2026-10-07T10:00:00Z',result:{observations:[observation],errors:[],automationKind:'repeat',comparison:{pairs:[pair]}}};
test('daily summary separates customer, candidate and provider evidence; deduplicates comparison pairs',()=>{const rows=[{...run,result:{...run.result,comparison:{pairs:[pair,pair]}}},{...run,id:'customer',entityType:'client',result:{measurementOrigin:'admin',observations:[{...observation,brandMentioned:false}],errors:[{provider:'ChatGPT',error:'timeout'}]}}];const r=summarizeDailyAnswerEvidence(rows);assert.equal(r.counts.runs,2);assert.equal(r.counts.neutralComplete,2);assert.equal(r.counts.brandMentions,1);assert.equal(r.counts.failed,1);assert.equal(r.counts.comparisonPairs,1);assert.equal(r.counts.appeared,1);assert.equal(r.groups.client.runs,1);assert.equal(r.groups.prospect.runs,1);assert.equal(r.automaticRepeat,1);assert.equal(r.manual,1);assert.equal(r.providers.find(x=>x.provider==='ChatGPT').failed,1);assert.equal(r.score,undefined)});
test('prompted, partial, unknown and mismatched comparisons never count as measured disappearance',()=>{const observations=[{...observation,brandPrompted:true},{...observation,truncated:true},{...observation,brandMentioned:undefined}];const r=summarizeDailyAnswerEvidence([{...run,result:{observations,errors:[{provider:'Gemini'}],comparison:{pairs:[pair]}}}]);assert.equal(r.counts.neutralComplete,0);assert.equal(r.counts.comparisonPairs,0);assert.equal(r.counts.notRepeated,0);assert.equal(r.counts.prompted,1);assert.equal(r.counts.incomplete,1);assert.equal(r.counts.unknown,1);assert.equal(r.counts.failed,1)});
test('a non-repeated brand match is scoped to the exact recorded pair; different models are excluded',()=>{const current={...observation,brandMentioned:false},changed={...pair,before:{brandMentioned:true},after:{brandMentioned:false}};const r=summarizeDailyAnswerEvidence([{...run,result:{observations:[current],errors:[],comparison:{pairs:[changed,{...changed,model:'different'}]}}}]);assert.equal(r.counts.notRepeated,1);assert.equal(r.counts.comparisonPairs,1);assert.match(r.scope,/genel görünürlük/)});
test('calendar validation rejects impossible dates and preserves Istanbul midnight',()=>{for(const value of ['2026-02-29','2026-02-31','2026-13-01','2026-1-1','0000-01-01','bad'])assert.equal(validReportDate(value),false,value);assert.equal(validReportDate('2028-02-29'),true);assert.equal(reportDay('2026-10-06T21:00:00Z'),'2026-10-07')});
const source=(await readFile(new URL('../lib/answer-evidence-daily.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const {dailyAnswerEvidence}=new Function('summarizeDailyAnswerEvidence','validReportDate',source+';return {dailyAnswerEvidence};')(summarizeDailyAnswerEvidence,validReportDate);
test('daily store uses indexed Istanbul date range, removes raw body and caps details',async()=>{let calls=0;const pool={query:async(sql,params)=>{calls++;assert.match(sql,/AT TIME ZONE 'Europe\/Istanbul'/);assert.match(sql,/created_at>=/);assert.match(sql,/created_at</);assert.match(sql,/x-'text'-'citations'-'usage'/);assert.match(sql,/LIMIT 1001/);assert.deepEqual(params,['2026-10-07']);return {rows:[{...run,totalRuns:'1'}]}}};const r=await dailyAnswerEvidence('2026-10-07',{pool});assert.equal(r.totalRuns,1);assert.equal(r.counts.comparisonPairs,1);assert.equal(r.limited,false);await assert.rejects(()=>dailyAnswerEvidence('2026-02-31',{pool}));assert.equal(calls,1)});

test('older runs with no recorded initiator are not attributed to the administrator',()=>{const r=summarizeDailyAnswerEvidence([{...run,result:{observations:[observation],errors:[]}}]);assert.equal(r.manual,0);assert.equal(r.unknownOrigin,1);assert.equal(r.latest[0].kind,'unknown')});
