import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const source=(await fs.readFile(new URL('../lib/email-delivery.js',import.meta.url),'utf8')).replace(/^import .*;$/gm,'').replace(/export /g,'');
const deliverOnce=new Function('databasePool','getDatabaseUrl','initializeSchema',source+';return deliverOnce')(()=>{},()=>'',async()=>{});
function fixture(){let row,locked=false,sends=0;const tx={async query(sql,a){if(sql.includes('pg_try')){if(locked)return {rows:[{acquired:false}]};locked=true;return {rows:[{acquired:true}]}}if(sql.includes('pg_advisory_unlock')){locked=false;return {rows:[]}}if(sql.startsWith('INSERT')){row||={payload:JSON.parse(a[1]),status:'sending',provider_id:'',first_attempt_at:new Date()};return {rows:[]}}if(sql.startsWith('SELECT'))return {rows:[row]};if(sql.includes("status='accepted'")){row.provider_id=a[1];row.status='accepted'}if(sql.includes("status='completed'"))row.status='completed';return {rows:[]}},release(){}};return {pool:{connect:async()=>tx},send:async()=>{sends++;return {id:'mail-1'}},get sends(){return sends},get row(){return row}}}
test('delivery persists payload, sends once and replays without finalizing twice',async()=>{const f=fixture();let finalized=0;await deliverOnce('operation',{subject:'original'},async()=>finalized++,f);const r=await deliverOnce('operation',{subject:'changed'},async()=>finalized++,f);assert.equal(f.sends,1);assert.equal(finalized,1);assert.equal(r.duplicate,true);assert.equal(f.row.payload.subject,'original')});
test('provider success followed by finalization failure resumes without another send',async()=>{const f=fixture();await assert.rejects(deliverOnce('operation',{},async()=>{throw Error('database-down')},f),/database-down/);assert.equal(f.row.status,'accepted');await deliverOnce('operation',{},async()=>{},f);assert.equal(f.sends,1)});
test('ambiguous sends older than the deduplication window stop for review',async()=>{const f=fixture();f.send=async()=>{throw Error('timeout')};await assert.rejects(deliverOnce('operation',{},async()=>{},f),/timeout/);f.row.first_attempt_at=new Date(Date.now()-24*3600000);await assert.rejects(deliverOnce('operation',{},async()=>{},f),/delivery-needs-review/)});
test('concurrent requests cannot both call the email provider',async()=>{const f=fixture();let unblock,started;const ready=new Promise(r=>started=r);f.send=async()=>{started();await new Promise(r=>unblock=r);return {id:'mail-1'}};const first=deliverOnce('operation',{},async()=>{},f);await ready;await assert.rejects(deliverOnce('operation',{},async()=>{},f),/delivery-in-progress/);unblock();await first});
