import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {answerEvidenceSelection} from '../lib/answer-evidence-selection.js';
import {reportDay,reportMarkets,validReportDate} from '../lib/reporting.js';
const source=(await readFile(new URL('../lib/implementation-report.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const {implementationReport}=new Function(source+';return {implementationReport};')();
const status={serverNow:'2026-10-07T13:45:00Z',hourlyUsed:true,readiness:{counts:{ready:1,waiting:1,blocked:15,recorded:2,review:1},reasons:{unpaid:15,baseline:15},reviewed:20,limited:false,scope:'First 100 work records.',entries:Array.from({length:20},(_,i)=>({workId:String(i),entityId:'client',state:i===0?'recorded':i===10?'review':'blocked',reasons:['unpaid']}))}};
test('executive snapshot preserves overlapping blockers, timestamp and bounded actionable details without mutating input',async()=>{const before=JSON.stringify(status);const r=await implementationReport({status:async scope=>{assert.deepEqual(scope,{entityType:'client'});return status}});assert.equal(r.snapshotType,'current');assert.equal(r.asOf,status.serverNow);assert.equal(r.entries.length,5);assert.equal(r.entries[0].state,'review');assert.ok(r.entries.every(x=>x.state!=='recorded'));assert.equal(r.counts.blocked,15);assert.equal(r.reasons.unpaid,15);assert.equal(r.reasons.baseline,15);assert.equal(JSON.stringify(status),before);assert.equal(r.historicalCounts,undefined)});
test('unavailable or undated source cannot manufacture zero counts',async()=>{for(const value of [{serverNow:'bad',readiness:status.readiness},{serverNow:status.serverNow}])await assert.rejects(()=>implementationReport({status:async()=>value}));await assert.rejects(()=>implementationReport({status:async()=>{throw Error('offline')}}))});
test('customer report links select correct entity; malformed and ambiguous links select no record',()=>{const id='01a11278-c210-7176-bc7f-0196dec182ec';assert.deepEqual(answerEvidenceSelection('?clientId='+id),{type:'client',id});assert.deepEqual(answerEvidenceSelection('?prospectId='+id),{type:'prospect',id});for(const q of ['?clientId=bad','?clientId='+id+'&prospectId='+id,''])assert.deepEqual(answerEvidenceSelection(q),{type:'prospect',id:''})});
const route=(await readFile(new URL('../app/api/executive-daily-report/route.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
function api({offline=false,denied=false}={}){let calls=0;const values={systemHealthReport:async()=>({available:true,snapshotType:'current'}),implementationReport:async()=>{calls++;if(offline)throw Error('unavailable');return {available:true,snapshotType:'current',asOf:status.serverNow}},dailyAnswerEvidence:async()=>({available:true,counts:{runs:3}}),reportDay,reportMarkets,validReportDate,requireAdmin:async()=>denied?Response.json({error:'auth'},{status:401}):null};for(const name of ['listDailyAgentReports','listSharedAgentEvents','listCreatorHuntLeads','getPredictiveRiskSignals','listMarketLearning','listPredictiveAlerts','listAutonomousActions','listStrategyLearning','listNextBestActions','getExperimentPerformance','listOpportunityForecasts','getProfitControlSnapshot','listProviderHealth'])values[name]=async()=>[];values.getExecutiveFunnelSnapshot=async()=>({prospects:{total:10,qualified:2}});return {GET:new Function(...Object.keys(values),route+';return GET;')(...Object.values(values)),calls:()=>calls}}
test('current customer snapshot coexists with a historical report date and optional failure preserves daily report',async()=>{for(const offline of [false,true]){const f=api({offline}),r=await f.GET(new Request('https://example.test/api/executive-daily-report?date=2026-10-01')),d=await r.json();assert.equal(r.status,200);assert.equal(d.date,'2026-10-01');assert.equal(d.answerEvidence.counts.runs,3);assert.equal(d.funnel.prospects.total,10);assert.equal(d.implementationTracking.available,!offline);if(offline){assert.equal(d.implementationTracking.counts,undefined);assert.match(d.implementationTracking.error,/bilinmiyor/)}else{assert.equal(d.implementationTracking.asOf,status.serverNow);assert.equal(d.implementationTracking.snapshotType,'current')}assert.equal(r.headers.get('cache-control'),'no-store')}});
test('report auth and invalid calendar dates prevent snapshot reads',async()=>{const f=api({denied:true});assert.equal((await f.GET(new Request('https://example.test/api/executive-daily-report'))).status,401);assert.equal(f.calls(),0);const g=api();assert.equal((await g.GET(new Request('https://example.test/api/executive-daily-report?date=2026-02-31'))).status,400);assert.equal(g.calls(),0)});
