import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const source=(await readFile(new URL('../lib/preparation-queue.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const {claimPreparation,finishPreparation,reservePreparationAI,enqueuePreparation}=new Function(source+';return {claimPreparation,finishPreparation,reservePreparationAI,enqueuePreparation}')();
test('claim uses atomic skip-locked lease with expiry recovery and bounded attempts',async()=>{let sql='',args;await claimPreparation({query:async(s,a)=>{sql=s;args=a;return {rows:[]}}},'analysis');assert.match(sql,/FOR UPDATE SKIP LOCKED/);assert.match(sql,/attempts<3/);assert.match(sql,/lease_until<NOW/);assert.match(sql,/lease_until=NOW\(\)\+INTERVAL '5 minutes'/);assert.equal(args[0],'analysis');assert.match(args[1],/^[0-9a-f-]{36}$/);await assert.rejects(()=>claimPreparation({},'send'),/invalid-stage/)});
test('finish requires active lease, never lets stale worker complete another claim',async()=>{await assert.rejects(()=>finishPreparation({query:async()=>({rows:[]})},{id:'job',leaseId:'old'}),/lease-lost/);let args;await finishPreparation({query:async(sql,a)=>{assert.match(sql,/lease_id=\$2 AND status='processing'/);args=a;return {rows:[{}]}}},{id:'job',leaseId:'lease'},{status:'waiting',refundAttempt:true,delaySeconds:3600});assert.equal(args[6],1);assert.equal(args[5],3600)});
async function reservation({used=0,valid=true,fail=false}={}){const statements=[];let release=0;const tx={query:async(sql)=>{statements.push(sql);if(sql.startsWith('SELECT count'))return {rows:[{used}]};if(sql.startsWith('SELECT id'))return {rows:valid?[{}]:[]};if(fail&&sql.startsWith('INSERT'))throw Error('db failed');return {rows:[]}},release(){release++}};const pool={connect:async()=>tx};let result,error;try{result=await reservePreparationAI(pool,{id:'job',leaseId:'lease'})}catch(e){error=e}return {statements,release,result,error}}
test('daily cap is transaction-locked and refuses the 51st attempt',async()=>{const r=await reservation({used:50});assert.equal(r.result,false);assert.ok(r.statements.some(s=>s.includes('pg_advisory_xact_lock')));assert.ok(!r.statements.some(s=>s.startsWith('INSERT')));assert.equal(r.release,1)});
test('reservation is committed before provider work, failure rolls back and releases',async()=>{const r=await reservation();assert.equal(r.result,true);assert.equal(r.statements.at(-1),'COMMIT');assert.equal(r.release,1);for(const options of [{valid:false},{fail:true}]){const failed=await reservation(options);assert.ok(failed.error);assert.equal(failed.statements.at(-1),'ROLLBACK');assert.equal(failed.release,1)}});
test('queue excludes blocked, customer, replied and contacted records before inserting',async()=>{let args;const pool={query:async(sql,a)=>{args=a;return {rows:[{id:'job'}]}}};const valid={id:'a',qualificationScore:90,qualificationLevel:'hot'};await enqueuePreparation([valid,{...valid,id:'blocked',selectionBlocked:true},{...valid,id:'sent',communicationStatus:'sent'},{...valid,id:'replied',replyStatus:'reply'},{...valid,id:'client',clientId:'customer'}],pool);const rows=JSON.parse(args[0]);assert.equal(rows.length,1);assert.equal(rows[0].id,'a')});
