import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {evaluateOutreachPool,needsProspectPreparation,selectPreparationCandidates} from '../lib/outreach-selection.js';
const source=(await readFile(new URL('../app/api/cron/daily-cycle/route.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
async function cycle({multiplier=1,fail=false,evidence=null}={}){
 let discovery=0,scans=0,release=0,unlock=0,active=0,peak=0;const candidates=Array.from({length:60},(_,i)=>({id:String(i),name:`Company ${i}`,status:'new',qualificationLevel:'hot',qualificationScore:80}));
 const client={query:async sql=>{if(sql.includes('unlock'))unlock++;return {rows:[{acquired:true}]}},release(){release++}};
 const deps={answerEvidenceStatus:async()=>({counts:{ready:0,cooldown:2,blocked:0},reviewed:2,hourlyUsed:true,serverNow:'2026-10-07T12:00:00Z',limited:false}),runAutomaticAnswerEvidence:async()=>evidence||({skipped:"fixture"}),evaluateOutreachPool,needsProspectPreparation,selectPreparationCandidates,nicheSearchSector:()=>'',databasePool:()=>({connect:async()=>client}),getDatabaseUrl:()=> 'configured',withRequestBudget:async(ms,fn)=>fn(),discoverBusinesses:async()=>{discovery++;return []},runProviderCheck:async prospect=>{scans++;active++;peak=Math.max(peak,active);await new Promise(r=>setTimeout(r,10));active--;if(fail&&prospect.id==='0')throw Error('provider-failed');return {score:20,provider:'Gemini',findings:['Verified improvement'],recommendations:['Add structured data']}},findPublicBusinessContact:async()=>({status:'not-found'}),getProspectNames:async()=>[],seedProspects:async()=>[],qualifyProspect:async()=>{},queueProspectScan:async()=>({id:'scan',status:'queued'}),completeProspectScan:async(scanId,id,result)=>{Object.assign(candidates.find(x=>x.id===id),{status:"analyzed",scanScore:result.score,scanProvider:result.provider,scanFindings:result.findings,scanRecommendations:result.recommendations});return {id:scanId}},getLatestProspectAnalysis:async()=>({score:20,provider:"Gemini"}),saveProspectContact:async()=>({contactStatus:'not-found'}),listOutreachEvaluationCandidates:async()=>candidates,addSharedAgentEvent:async()=>{},saveDailyAgentReport:async()=>({id:'report'}),learnFromMarketRun:async()=>{},listMarketLearning:async()=>[],refreshMarketEconomics:async()=>{},listLearnedPolicies:async()=>[],refreshBudgetGuard:async()=>({mode:multiplier<1?'guarded':'normal',multiplier}),process:{env:{AUTO_HUNT_SECRET:'fixture-key'}},console:{log(){},error(){}}};
 const get=new Function(...Object.keys(deps),source+';return GET;')(...Object.values(deps));
 const r=await get(new Request('https://example.com/api/cron/daily-cycle',{headers:{authorization:'Bearer fixture-key'}}));const report=await r.json();
 return {r,report,discovery,scans,release,unlock,peak};
}
test('large pool runs two scans concurrently and prepares at most one contact package',async()=>{
 const {r,report,discovery,scans,release,unlock,peak}=await cycle();
 assert.equal(r.status,200);assert.equal(report.mode,'backlog-preparation');assert.equal(discovery,0);assert.equal(scans,2);assert.equal(report.completed,2);assert.equal(report.preparedCandidates.filter(x=>x.stage==="analysis").length,2);assert.equal(report.preparedCandidates.filter(x=>x.stage==="contact-package").length,1);assert.equal(peak,2);assert.equal(report.poolAfter.awaitingAnalysis,58);assert.equal(release,1);assert.equal(unlock,1);
});
test('guarded budget lowers capacity to one scan',async()=>{const {report,scans,peak}=await cycle({multiplier:.5});assert.equal(scans,1);assert.equal(peak,1);assert.equal(report.completed,1);assert.equal(report.capacity.analysisLimit,1)});
test('one failed scan does not erase the successful concurrent result',async()=>{const {report,scans,release}=await cycle({fail:true});assert.equal(scans,2);assert.equal(report.completed,1);assert.equal(report.errors.length,1);assert.equal(report.errors[0].stage,'analysis');assert.equal(report.poolAfter.awaitingAnalysis,59);assert.equal(release,1)});

test('scheduled repeat details reach the daily report without replacing saved scans or contact capacity',async()=>{const {report}=await cycle({evidence:{id:'repeat-run',kind:'repeat',entityId:'old',entityName:'Older Company',slotAuditSaved:true,result:{summary:{successful:1,failed:0},errors:[],comparison:{pairs:[{}]}}}});assert.equal(report.answerEvidence.kind,'repeat');assert.equal(report.answerMonitoring.counts.cooldown,2);assert.equal(report.answerMonitoring.hourlyUsed,true);assert.equal(report.answerEvidence.comparisonPairs,1);assert.equal(report.answerEvidence.id,'repeat-run');assert.equal(report.completed,2);assert.equal(report.capacity.contactLimit,1)});
