import {reviewedGuidance} from '../lib/source-review.js';
import {validEnquiryEvidence} from '../lib/verified-enquiry.js';
import {evaluateOutreachPool} from '../lib/outreach-selection.js';
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const source=(await readFile(new URL('../lib/preparation-worker.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'').replace(/const dependencies=\{[^;]+;/,'const dependencies={};');
const {runPreparation,validSavedAnalysis}=new Function('PREPARATION_STAGES','evaluateOutreachPool','validEnquiryEvidence','reviewedGuidance',source+';return {runPreparation,validSavedAnalysis}')(['preflight','analysis','contact'],evaluateOutreachPool,validEnquiryEvidence,reviewedGuidance);
const analysis={score:40,provider:'Gemini',findings:['Observed provider assessment'],recommendations:['Check structured service information']};
async function run(stage,{cached=null,contact=true,guard={mode:'normal',multiplier:1,dailyBudget:0},reserved=true,eligible=true,failedScan=false,official=true}={}){
 const calls=[],finishes=[],next=[];let count=0;
 const prospect={id:'prospect',name:'Company',domain:'company.com',qualificationScore:80,contactEmail:'info@company.com',contactSourceUrl:'https://company.com/contact',contactStatus:'verified',enquiryEvidence:official?{method:'official-enquiry-v1',checkedAt:new Date().toISOString(),inspection:{method:'official-html-v1',status:'checked',sourceUrl:'https://company.com'}}:{},replyStatus:eligible?'':'replied'};
 const deps={preparationPool:async()=>({}),listOutreachEvaluationCandidates:async()=>[prospect],enqueuePreparation:async()=>1,claimPreparation:async()=>count++===0?{id:'job',prospectId:'prospect',attempts:1,priority:10,payload:{}}:null,finishPreparation:async(p,j,value={})=>finishes.push(value),enqueueNext:async(p,j,s,payload)=>next.push({stage:s,payload}),getCommunicationProspect:async()=>prospect,getLatestProspectAnalysis:async()=>cached,preflightProspect:async()=>{calls.push('preflight');return {inspection:official?{method:'official-html-v1',status:'checked',sourceUrl:'https://company.com'}:null,contact:{status:contact?'verified':'not-found',email:contact?'info@company.com':'',sourceUrl:'https://company.com/contact'}}},saveEnquiryEvidence:async()=>({id:'prospect'}),saveProspectContact:async()=>({contactStatus:'verified'}),refreshBudgetGuard:async()=>guard,reservePreparationAI:async()=>{calls.push('reserve');return reserved},queueProspectScan:async()=>({id:'scan'}),withRequestBudget:async(ms,fn)=>fn(),runProviderCheck:async()=>{calls.push('AI');if(failedScan)throw Error('secret api key');return analysis},completeProspectScan:async()=>({id:'scan'}),verifyContactPage:async()=>{calls.push('verify');return contact},personalizeProspectOutreach:async()=>{calls.push('personalize');return {}},saveProspectPersonalization:async()=>({id:'prospect'}),buildProspectProposal:async()=>({}),saveProspectProposal:async()=>({id:'prospect'}),prepareProspectCommunication:async()=>({id:'prospect'}),saveDailyAgentReport:async()=>({id:'report'}),addSharedAgentEvent:async()=>{}};
 const report=await runPreparation(stage,{deps});return {report,calls,finishes,next};
}
test('missing official contact stops before paid analysis and remains retryable',async()=>{const r=await run('preflight',{contact:false});assert.deepEqual(r.calls,['preflight']);assert.equal(r.next.length,0);assert.equal(r.finishes[0].status,'waiting');assert.equal(r.report.waiting,1)});
test('preflight reuses completed analysis and directly queues contact',async()=>{const r=await run('preflight',{cached:analysis});assert.equal(r.next[0].stage,'contact');assert.equal(r.report.reused,1);assert.ok(!r.calls.includes('AI'))});
test('analysis replay reuses stored result without paid reservation',async()=>{const r=await run('analysis',{cached:analysis});assert.deepEqual(r.calls,[]);assert.equal(r.report.reused,1);assert.equal(r.next[0].stage,'contact')});
test('legacy analysis queue bypasses AI budgets and prepares official enquiries',async()=>{for(const args of [{guard:{mode:'emergency',dailyBudget:10}},{guard:{mode:'normal'}},{reserved:false}]){const r=await run('analysis',args);assert.deepEqual(r.calls,['preflight']);assert.equal(r.next[0].stage,'contact');assert.equal(r.report.scanned,0)}});
test('no official page means no invented assessment or contact package',async()=>{const r=await run('analysis',{official:false});assert.ok(!r.calls.includes('AI'));assert.equal(r.finishes[0].status,'waiting');assert.equal(r.next.length,0)});
test('new preflight directly queues contact without provider analysis',async()=>{const r=await run('preflight');assert.equal(r.next[0].stage,'contact');assert.ok(!r.calls.includes('AI'))});
test('contact preparation rechecks source, creates drafts, never sends',async()=>{const r=await run('contact',{cached:analysis});assert.deepEqual(r.calls,['verify','personalize']);assert.equal(r.report.contactPrepared,1)});
test('invalid contact and replied prospects cannot produce communication packages',async()=>{const invalid=await run('contact',{cached:analysis,contact:false});assert.equal(invalid.report.contactPrepared,0);assert.ok(!invalid.calls.includes('personalize'));const replied=await run('analysis',{eligible:false});assert.equal(replied.calls.length,0);assert.equal(replied.report.skipped,1)});
test('invalid, synthetic and incomplete analyses never count as reusable',()=>{assert.equal(validSavedAnalysis(analysis),true);for(const x of [{...analysis,score:null},{...analysis,provider:'synthetic'},{...analysis,findings:[]},{...analysis,score:101}])assert.equal(validSavedAnalysis(x),false)});
