import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {evaluateOutreachPool,needsProspectPreparation,selectPreparationCandidates} from '../lib/outreach-selection.js';
import {salesCycleMode} from '../lib/sales-cycle-mode.js';
const source=(await readFile(new URL('../app/api/cron/daily-cycle/route.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
async function cycle({multiplier=1,fail=false,evidence=null,claimableTotal=0}={}){
 let discovery=0,scans=0,release=0,unlock=0,active=0,peak=0;const candidates=Array.from({length:60},(_,i)=>({id:String(i),name:`Company ${i}`,status:'new',qualificationLevel:'hot',qualificationScore:80}));
 const client={query:async sql=>{if(sql.includes('unlock'))unlock++;return {rows:[{acquired:true}]}},release(){release++}};
 const availability=()=>({claimableTotal,stages:{preflight:{claimable:claimableTotal,waitingFuture:0,needsReview:0,attemptsExhausted:0,done:0},analysis:{claimable:0,waitingFuture:0,needsReview:0,attemptsExhausted:0,done:0},contact:{claimable:0,waitingFuture:0,needsReview:0,attemptsExhausted:0,done:0}},asOf:'2026-10-07T12:00:00Z'});
 const deps={enqueuePreparation:async rows=>rows.length,preparationAvailability:async()=>availability(),salesCycleMode,reportDay:()=> '2026-10-07',dailyAnswerEvidence:async()=>({date:'2026-10-07',counts:{runs:3,neutralComplete:3,comparisonPairs:0,failed:0},totalRuns:3,limited:false}),answerEvidenceStatus:async()=>({counts:{ready:0,cooldown:2,blocked:0},reviewed:2,hourlyUsed:true,serverNow:'2026-10-07T12:00:00Z',limited:false}),runAutomaticAnswerEvidence:async()=>evidence||({skipped:"fixture"}),evaluateOutreachPool,needsProspectPreparation,selectPreparationCandidates,nicheSearchSector:()=>'',databasePool:()=>({connect:async()=>client}),getDatabaseUrl:()=> 'configured',withRequestBudget:async(ms,fn)=>fn(),discoverBusinesses:async()=>{discovery++;return []},runProviderCheck:async prospect=>{scans++;active++;peak=Math.max(peak,active);await new Promise(r=>setTimeout(r,10));active--;if(fail&&prospect.id==='0')throw Error('provider-failed');return {score:20,provider:'Gemini',findings:['Verified improvement'],recommendations:['Add structured data']}},findPublicBusinessContact:async()=>({status:'not-found'}),getProspectNames:async()=>[],seedProspects:async()=>[],qualifyProspect:async()=>{},queueProspectScan:async()=>({id:'scan',status:'queued'}),completeProspectScan:async(scanId,id,result)=>{Object.assign(candidates.find(x=>x.id===id),{status:"analyzed",scanScore:result.score,scanProvider:result.provider,scanFindings:result.findings,scanRecommendations:result.recommendations});return {id:scanId}},getLatestProspectAnalysis:async()=>({score:20,provider:"Gemini"}),saveProspectContact:async()=>({contactStatus:'not-found'}),listOutreachEvaluationCandidates:async()=>candidates,addSharedAgentEvent:async()=>{},saveDailyAgentReport:async()=>({id:'report'}),learnFromMarketRun:async()=>{},listMarketLearning:async()=>[],refreshMarketEconomics:async()=>{},listLearnedPolicies:async()=>[],refreshBudgetGuard:async()=>({mode:multiplier<1?'guarded':'normal',multiplier}),process:{env:{AUTO_HUNT_SECRET:'fixture-key'}},console:{log(){},error(){}}};
 const get=new Function(...Object.keys(deps),source+';return GET;')(...Object.values(deps));
 const r=await get(new Request('https://example.com/api/cron/daily-cycle',{headers:{authorization:'Bearer fixture-key'}}));const report=await r.json();
 return {r,report,discovery,scans,release,unlock,peak};
}
test('large non-actionable backlog no longer starves discovery',async()=>{
 const {r,report,discovery,scans,release,unlock}=await cycle({claimableTotal:0});
 assert.equal(r.status,200);assert.equal(report.mode,'discovery-and-preparation');assert.ok(discovery>0);assert.equal(scans,0);assert.equal(report.completed,0);assert.equal(report.preparation.reviewed,60);assert.equal(report.poolAfter.awaitingAnalysis,60);assert.equal(report.queueAvailability.claimableTotal,0);assert.equal(release,1);assert.equal(unlock,1);
});
test('large actionable backlog still prioritizes preparation safely',async()=>{
 const {r,report,discovery}=await cycle({claimableTotal:2});
 assert.equal(r.status,200);assert.equal(report.mode,'backlog-preparation');assert.equal(discovery,0);assert.equal(report.preparation.reviewed,60);assert.equal(report.queueAvailability.claimableTotal,2);
});
test('guarded scheduler queues work without paid preparation',async()=>{const {report,scans}=await cycle({multiplier:.5});assert.equal(scans,0);assert.equal(report.preparation.reviewed,60);assert.equal(report.capacity.analysisLimit,0)});
test('scheduled repeat details and daily monitoring survive queue separation',async()=>{const {report}=await cycle({evidence:{id:'repeat-run',kind:'repeat',entityId:'old',entityName:'Older Company',slotAuditSaved:true,result:{summary:{successful:1,failed:0},errors:[],comparison:{pairs:[{}]}}}});assert.equal(report.answerEvidence.kind,'repeat');assert.equal(report.answerMonitoring.counts.cooldown,2);assert.equal(report.answerMonitoring.hourlyUsed,true);assert.equal(report.answerMonitoring.daily.counts.runs,3);assert.equal(report.answerEvidence.comparisonPairs,1);assert.equal(report.answerEvidence.id,'repeat-run');assert.equal(report.completed,0)});
