import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const lockSource=(await fs.readFile(new URL('../lib/remeasurement-lock.js',import.meta.url),'utf8')).replace(/^import .*;$/gm,'').replace(/export /g,'');
const withLock=new Function('databasePool','getDatabaseUrl',lockSource+';return withRemeasurementLock')(()=>{},()=> 'db');
function poolFixture({failUnlock=false}={}){let held=false;const releases=[];return {releases,pool:{connect:async()=>({async query(sql){if(sql.includes('pg_try')){const acquired=!held;if(acquired)held=true;return {rows:[{acquired}]}}if(failUnlock)throw Error('unlock-failed');held=false;return {rows:[]}},release(destroy){releases.push(destroy)}})}}}
test('parallel cycles cannot both run; lock is released after success',async()=>{const f=poolFixture();let start,finish;const ready=new Promise(r=>start=r);const first=withLock(async()=>{start();await new Promise(r=>finish=r);return 'done'},f);await ready;assert.equal((await withLock(async()=>assert.fail('duplicate cycle'),f)).skipped,'already-running');finish();assert.equal(await first,'done');assert.equal(await withLock(async()=> 'again',f),'again')});
test('failed work releases lock; failed unlock destroys the pooled connection',async()=>{const f=poolFixture();await assert.rejects(withLock(async()=>{throw Error('provider-failed')},f),/provider-failed/);assert.equal(await withLock(async()=> 'retry',f),'retry');const bad=poolFixture({failUnlock:true});await withLock(async()=> 'ok',bad);assert.deepEqual(bad.releases,[true])});
const route=(await fs.readFile(new URL('../app/api/remeasurement-cycle/route.js',import.meta.url),'utf8')).replace(/^import .*;$/gm,'').replace(/export /g,'');
function cycleFixture({eligible=[true,true],comparison=null,budget=Infinity,failActivity=false}={}){
 let check=0,created=0,providers=0,completed=0,failed=0;
 const clients=[{id:'client',name:'Business',domain:'example.com'}];
 const GET=new Function('withRemeasurementLock','withRequestBudget','remainingBudget','heartbeatComponent','getClientsReadyForRemeasurement','createScan','completeScan','failScan','getScanComparison','addClientActivityEvent','getClientProfile','runLocalizedProviderChecks','syncFindingsFromScan',route+';return GET')(async run=>run(),async(_ms,run)=>run(),()=>budget,async()=>{},async(_n,id)=>id?(eligible[check++]?[clients[0]]:[]):clients,async()=>{created++;return {id:'scan',persisted:true}},async()=>{completed++;return {id:'scan'}},async()=>{failed++},async()=>comparison,async()=>{if(failActivity)throw Error('activity-failed')},async()=>({}),async()=>{providers++;return {results:[{score:42}]}},async()=>{});
 return {GET,get counts(){return {created,providers,completed,failed}}};
}
function request(){process.env.CRON_SECRET='test';return new Request('https://example.com/api',{headers:{authorization:'Bearer test'}})}
test('eligibility is rechecked before provider spend and before completing scan',async()=>{const before=cycleFixture({eligible:[false]});const skipped=await (await before.GET(request())).json();assert.equal(skipped.skipped[0].reason,'eligibility-changed');assert.equal(before.counts.providers,0);const during=cycleFixture({eligible:[true,false]});const failed=await (await during.GET(request())).json();assert.equal(failed.errors[0].error,'eligibility-changed-during-scan');assert.deepEqual(during.counts,{created:1,providers:1,completed:0,failed:1})});
test('missing comparison is uncompared; activity failures never erase completed scan',async()=>{const f=cycleFixture({failActivity:true});const result=await (await f.GET(request())).json();assert.equal(result.uncompared,1);assert.equal(result.unchanged,0);assert.equal(f.counts.completed,1);assert.equal(f.counts.failed,0);assert.equal(result.errors[0].error,'activity-failed')});
test('time budget defers work before creating a scan; unauthenticated scheduler cannot run',async()=>{const f=cycleFixture({budget:1000});assert.equal((await (await f.GET(request())).json()).deferred,1);assert.equal(f.counts.created,0);assert.equal((await f.GET(new Request('https://example.com/api'))).status,401)});
