import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import {wordpressObservation,wordpressTarget,draftContent} from '../lib/wordpress-validation.js';
const id='11111111-1111-1111-1111-111111111111',post={id:10,type:'post',slug:'aiv-'+id,status:'draft'};
test('WordPress observations require an exact post identity and distinguish draft from published',()=>{assert.equal(wordpressObservation([post],id).status,'draft-created');assert.equal(wordpressObservation({...post,status:'publish'},id,10).published,true);assert.equal(wordpressObservation([],id),null);for(const x of [[post,post],[{...post,slug:'another-task'}],[{...post,type:'page'}],[{...post,id:-1}],[{...post,status:'invalid'}]])assert.throws(()=>wordpressObservation(x,id));assert.throws(()=>wordpressObservation(post,id,11))});
const source=(await fs.readFile(new URL('../lib/wordpress-drafts.js',import.meta.url),'utf8')).slice((await fs.readFile(new URL('../lib/wordpress-drafts.js',import.meta.url),'utf8')).indexOf('export async function reconcileWordpressDelivery')).replace('export ','');
function fixture({remote=[post],delivery={status:'delivery-unknown',post_id:null},failAudit=false,domain='example.com'}={}){
 let stored={...delivery},snapshot;const calls=[],requests=[];
 const tx={release(){calls.push('release')},async query(sql,a){calls.push(sql);if(sql==='BEGIN')snapshot={...stored};if(sql==='ROLLBACK')stored=snapshot;if(sql.startsWith('SELECT w.*'))return {rows:[{client_id:'client',source:'implementation-agent',domain}]};if(sql.startsWith('SELECT * FROM cms_deliveries'))return {rows:[stored]};if(sql.startsWith('UPDATE cms_deliveries'))stored={status:a[1],post_id:a[2]};if(sql.startsWith('INSERT INTO client_activity')&&failAudit)throw Error('audit-failed');return {rows:[]}}};
 const reconcile=new Function('crypto','cmsPool','wordpressTarget','safePublicHost','budgetFetch','wordpressObservation',source+';return reconcileWordpressDelivery')(crypto,async()=>({connect:async()=>tx}),wordpressTarget,async()=>{},async(url,options)=>{requests.push({url,options});assert.equal(options.method,'GET');assert.equal(options.redirect,'error');return {ok:true,json:async()=>remote}},wordpressObservation);
 return {calls,requests,reconcile,get stored(){return stored}};
}
function configure(){process.env.WORDPRESS_SITE_URL='https://example.com';process.env.WORDPRESS_USERNAME='test';process.env.WORDPRESS_APPLICATION_PASSWORD='test'}
test('unknown delivery is recovered through read-only lookup without completing work',async()=>{configure();const f=fixture();const r=await f.reconcile(id);assert.equal(r.status,'draft-created');assert.equal(r.workCompleted,false);assert.equal(f.stored.post_id,10);assert.ok(f.requests[0].url.includes('slug=aiv-'));assert.ok(!f.calls.some(x=>x.startsWith('UPDATE work_items')));assert.ok(f.calls.includes('COMMIT'))});
test('missing remote record keeps the unknown marker and never enables duplicate creation',async()=>{configure();const f=fixture({remote:[]});const r=await f.reconcile(id);assert.equal(r.duplicateCreationAllowed,false);assert.equal(f.stored.status,'delivery-unknown');assert.ok(!f.calls.some(x=>x.startsWith('UPDATE')))});
test('known post is queried by ID and a published observation remains separate from work completion',async()=>{configure();const f=fixture({remote:{...post,status:'publish'},delivery:{status:'draft-created',post_id:'10'}});const r=await f.reconcile(id);assert.ok(f.requests[0].url.includes('/posts/10?'));assert.equal(r.status,'published-observed');assert.equal(r.workCompleted,false)});
test('wrong customer site prevents external requests and audit failure rolls back reconciliation',async()=>{configure();const wrong=fixture({domain:'other.com'});await assert.rejects(wrong.reconcile(id),/client-site-mismatch/);assert.equal(wrong.requests.length,0);const f=fixture({failAudit:true});await assert.rejects(f.reconcile(id),/audit-failed/);assert.equal(f.stored.status,'delivery-unknown');assert.ok(f.calls.includes('ROLLBACK'));assert.ok(!f.calls.includes('COMMIT'))});
