"use client";
import {useEffect,useState} from 'react';
export default function AnswerEvidenceManager(){
 const [type,setType]=useState('prospect'),[id,setId]=useState(''),[prospects,setProspects]=useState([]),[clients,setClients]=useState([]),[runs,setRuns]=useState([]),[providers,setProviders]=useState([]),[queries,setQueries]=useState(''),[language,setLanguage]=useState('tr'),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 async function json(url){const r=await fetch(url,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Kayıtlar alınamadı.');return d}
 async function load(entityId=id,entityType=type){setLoading(true);const settled=await Promise.allSettled([json('/api/prospects').then(d=>setProspects(d.prospects||[])),json('/api/clients').then(d=>setClients(d.clients||[])),json('/api/answer-evidence'+(entityId?'?entityType='+entityType+'&entityId='+encodeURIComponent(entityId):'')).then(d=>{setRuns(d.runs||[]);setProviders(d.providers||[])})]);const errors=settled.filter(x=>x.status==='rejected').map(x=>x.reason.message);if(errors.length)setMessage(errors.join(' · '));setLoading(false)}
 useEffect(()=>{const initial=new URLSearchParams(window.location.search).get('prospectId');if(initial)setId(initial);load(initial||'','prospect')},[]);
 useEffect(()=>{if(!id)return;let active=true;json('/api/answer-evidence?entityType='+type+'&entityId='+encodeURIComponent(id)).then(d=>{if(active){setRuns(d.runs||[]);setProviders(d.providers||[])}}).catch(e=>{if(active)setMessage(e.message)});return()=>{active=false}},[type,id]);
 const choices=type==='prospect'?prospects:clients,visible=id?runs.filter(x=>x.entityId===id&&x.entityType===type):runs;
 async function run(e){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/answer-evidence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entityType:type,entityId:id,queries:queries.split('\n').map(x=>x.trim()).filter(Boolean),language})}),d=await r.json();if(!r.ok)throw Error(d.run?.skipped==='recent-run'?'Bu işletmenin son 15 dakika içinde kaydı var; yeniden çağrı yapılmadı.':d.run?.skipped==='already-running'?'Bu işletme için tur zaten çalışıyor.':d.run?.skipped==='ai-budget-exhausted'?'AI bütçe sınırı nedeniyle tur bekliyor.':d.error||'Tur tamamlanamadı.');setMessage(`${d.run.result.summary.successful} yanıt kaydedildi · ${d.run.result.summary.failed} hata. Başarısız çağrılar yokluk kanıtı değildir.`);await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <section style={{display:'grid',gap:14}}><article className="panel"><h2>AI yanıt örneği topla</h2><p>Markayı belirtmeyen sektör ve konum sorguları kullanın. Marka adı geçen sorgular yönlendirici olarak işaretlenir. API yanıtları, tüketici uygulamalarındaki sonuçlarla aynı kabul edilmez.</p><small>Bağlı sağlayıcılar: {providers.join(' · ')||'Yükleniyor veya sağlayıcı yapılandırılmamış'} · Tur başına en fazla 2 sorgu × 3 sağlayıcı. Aynı işletme için 15 dakika aralık.</small>
 <form onSubmit={run} style={{display:'grid',gap:12,marginTop:14}}><label>Kayıt türü<select value={type} onChange={e=>{setType(e.target.value);setId('');setRuns([])}}><option value="prospect">İşletme adayı</option><option value="client">Müşteri</option></select></label><label>İşletme<select required value={id} onChange={e=>setId(e.target.value)}><option value="">Bir işletme seçin</option>{choices.map(x=><option key={x.id} value={x.id}>{x.name} · {x.city||x.domain}</option>)}</select></label><label>Otomatik sorgu dili<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="tr">Türkçe</option><option value="en">English</option></select></label><label>Sorgular (isteğe bağlı, en fazla 2; her satıra bir sorgu)<textarea rows={3} maxLength={1001} value={queries} onChange={e=>setQueries(e.target.value)} placeholder="Örn. Ankara'da diş kliniği önerir misiniz?"/></label><small>Boş bırakırsanız işletmenin kayıtlı sektör ve konumundan bir sorgu hazırlanır. Marka ve alan adı sağlayıcıya ayrıca verilmez.</small><button disabled={busy||loading||!id||!providers.length}>{busy?'Yanıtlar toplanıp kaydediliyor…':'Yanıt kanıtı topla'}</button></form>{message&&<p role="status">{message}</p>}</article>
 <article className="panel"><div className="section-title"><h2>Kaydedilen yanıtlar (son 20 tur)</h2><button onClick={()=>load()} disabled={loading||busy}>Yenile</button></div>{loading?<p>Yükleniyor…</p>:!visible.length?<p>Bu seçime ait kayıt yok. Eski sağlayıcı tahminleri yanıt kanıtı olarak gösterilmez.</p>:visible.map(run=><article className="panel" key={run.id} style={{marginTop:14,overflowWrap:'anywhere'}}><h3>{run.entityName}</h3><small>{new Date(run.createdAt).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})}</small><p>{run.result.summary.neutralComplete?`${run.result.summary.brandMentions}/${run.result.summary.neutralComplete} tamamlanmış, markasız sorgu yanıtında tam marka adı veya alan adı bulundu · ${run.result.summary.officialCitations} yanıtta resmî alan adına kaynak referansı var.`:"Tamamlanmış markasız sorgu yanıtı yok; eşleşme sonucu bilinmiyor."}</p><small>{run.result.summary.scope}</small>{run.result.observations.map((x,i)=><details key={i} style={{marginTop:14}}><summary>{x.provider} · {x.brandPrompted?'Marka içeren sorgu':x.truncated?'Eksik/kısaltılmış yanıt':x.brandMentioned?'Marka eşleşmesi bulundu':'Tam ad/alan adı eşleşmedi'}</summary><div style={{display:'grid',gap:10,marginTop:10}}><b>Sorgu: {x.query}</b><small>Model: {x.model} · Mod: {x.mode} · {new Date(x.checkedAt).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})}</small><small>Yanıt kimliği: {x.responseId||'Sağlayıcı döndürmedi'}</small><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontFamily:'inherit'}}>{x.text}</pre><b>Sağlayıcı yanıtındaki kaynak referansları</b>{x.citations.length?<ul>{x.citations.map((s,j)=><li key={j}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title||s.url} ↗</a></li>)}</ul>:<p>Kaynak referansı dönmedi. Yanıtta yazılan rastgele bağlantılar doğrulanmış kaynak sayılmaz.</p>}{x.truncated&&<p>Yanıt tamamlanmadı veya kayıt sınırını aştı; tarafsız örnek sayımına dahil edilmedi.</p>}</div></details>)}{run.result.errors.map((x,i)=><p key={i} role="status">{x.provider} · {x.query}: {x.error}</p>)}</article>)}</article></section>;
}
