import {evidenceWaitLabels} from '../lib/answer-evidence-status-rules.js';
const date=value=>value&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'}):'—';
const reasons={'recent-run':'Yakın tarihli ölçüm nedeniyle bekletildi.','already-running':'Eş zamanlı ölçüm nedeniyle çağrı yapılmadı.','ai-budget-exhausted':'AI bütçe sınırı nedeniyle çağrı yapılmadı.','provider-response-failed':'Sağlayıcı çağrısında hata kaydedildi.','evidence-run-unavailable':'Ölçüm tamamlanamadı; bu saate ait hak tekrar kullanılmaz.'};
export default function AnswerEvidenceStatus({data}){
 if(!data)return <article className="panel"><h2>Otomatik ölçüm takibi</h2><p>Durum yükleniyor…</p></article>;
 if(data.error)return <article className="panel"><h2>Otomatik ölçüm takibi</h2><p role="status">{data.error}</p></article>;
 if(!data.supported)return <article className="panel"><h2>Otomatik ölçüm takibi</h2><p>{data.scope}</p></article>;
 return <article className="panel" style={{overflowWrap:'anywhere'}}><h2>Otomatik ölçüm takibi</h2><p>{data.scope}</p><dl style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))',gap:12}}>{[['Yeniden ölçüme uygun',data.counts.ready],['24 saat bekleyen',data.counts.cooldown],['Koşulu eksik / kapsam dışı',data.counts.blocked]].map(([label,count])=><div className="panel" key={label}><dt>{label}</dt><dd style={{fontSize:28,fontWeight:700,margin:0}}>{count}</dd></div>)}</dl><small>{data.reviewed} aday değerlendirildi · Güncelleme: {date(data.serverNow)}{data.limited?' · İlk 1000 kayıt gösteriliyor; sayımlar bu görünümle sınırlı.':''}</small><p>{data.hourlyUsed?`Bu saatin otomatik ölçüm hakkı kullanıldı. Saatlik sınır ${date(data.nextHourAt)} itibarıyla yenilenir.`:'Bu saatte kaydedilmiş otomatik ölçüm denemesi yok.'}</p><small>Uygunluk zamanı bir çalışma sözü değildir. Ajan turunun süresi, bütçesi ve sıradaki aday seçimi ölçümü erteleyebilir.</small>
 {!!Object.keys(data.reasons).length&&<details style={{marginTop:14}}><summary>Eksik koşullar ve kapsam</summary><ul>{Object.entries(data.reasons).map(([reason,count])=><li key={reason}>{evidenceWaitLabels[reason]||'Koşul doğrulanamadı'}: {count}</li>)}</ul></details>}
 <details style={{marginTop:14}}><summary>Tekrar ölçümü için ilk 10 kayıt</summary>{data.entries.length?data.entries.map(x=><div key={x.entityId} className="panel" style={{marginTop:10}}><b>{x.entityName}</b><p>{x.label}</p><small>Son ölçüm / otomatik deneme: {date(x.lastAttemptAt)}{x.nextEligibleAt&&<> · En erken uygunluk: {date(x.nextEligibleAt)}</>}</small></div>):<p>Bu kapsamda kayıtlı yanıtı bulunan aday yok.</p>}</details>
 <details style={{marginTop:14}} open><summary>Son otomatik denemeler</summary>{data.attempts.length?data.attempts.map(x=><div className="panel" key={x.slot} style={{marginTop:10}}><b>{x.entityName||'Aday kaydı bulunamadı'} · {x.kind==='repeat'?'Tekrar ölçümü':'İlk örnek'}</b><p>{x.status==='claimed'?'Başlatma kaydı var; sonuç henüz doğrulanmadı.':x.status==='completed'&&x.runId?'Yanıt kaydı tamamlandı.':x.status==='needs-attention'?'Yanıt kaydedildi; sağlayıcı hatası ayrıca incelenmeli.':x.status==='skipped'?'Çağrı bekletildi.':x.status==='failed'?'Ölçüm tamamlanamadı.':'Sonuç doğrulanamadı.'}</p>{x.reason&&<p>{reasons[x.reason]||'Bekleme nedeni kaydedildi; ayrıntı doğrulanamadı.'}</p>}<small>{date(x.createdAt)}{x.runId&&<> · Yanıt kaydı: {x.runId}</>}</small></div>):<p>Bu kapsamda otomatik deneme kaydı yok.</p>}</details></article>;
}
