"use client";
import InboxManager from "./InboxManager";
import {useEffect,useState} from "react";
export default function CommunicationCenter(){
 const [rows,setRows]=useState([]),[msg,setMsg]=useState("");
 const [sender,setSender]=useState(null),[drafts,setDrafts]=useState({}),[sending,setSending]=useState(""),[sent,setSent]=useState([]);
 const [deliveryEvents,setDeliveryEvents]=useState({});
 const [automation,setAutomation]=useState(null),[autoBusy,setAutoBusy]=useState(false);
 async function loadAutomation(){const r=await fetch('/api/outreach-cycle',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Otomatik iletişim bilgisi alınamadı');setAutomation(d)}
 async function runAutomation(dryRun){setAutoBusy(true);setMsg('');try{const r=await fetch('/api/outreach-cycle',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dryRun})}),d=await r.json();if(!r.ok)throw Error(d.error||d.errors?.[0]?.error||'Tur tamamlanamadı');setMsg(`${dryRun?'Gönderimsiz kontrol':'İletişim turu'}: ${d.eligible} uygun aday, ${d.firstSent} ilk temas, ${d.followSent} takip. ${d.errors?.length||0} doğrulama hatası. ${d.deferred||d.skippedReason||''}`);await loadAutomation();await load()}catch(e){setMsg(e.message)}finally{setAutoBusy(false)}}
 useEffect(()=>{loadAutomation().catch(e=>setMsg(e.message))},[]);
 async function checkDelivery(id){try{const r=await fetch("/api/communication-send",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"delivery-status",emailId:id})}),d=await r.json().catch(()=>({error:`Teslimat sorgusu geçerli yanıt vermedi (HTTP ${r.status}); teslimat doğrulanamadı.`}));if(!r.ok||d.error)throw Error(d.error);setDeliveryEvents(e=>({...e,[id]:d.event}))}catch(e){setMsg(e.message)}}
 async function send(x){setSending(x.id);setMsg("");try{const r=await fetch("/api/communication-send",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({prospectId:x.id,draft:x.outreachDraft})}),d=await r.json();if(!r.ok)throw Error(d.error+(d.detail?` (${d.detail})`:""));setSent(s=>[...s,{name:x.name,email:x.contactEmail,id:d.delivery?.id}]);await load()}catch(e){setMsg(e.message)}finally{setSending("")}}
 async function load(){try{const r=await fetch("/api/communication-queue",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error||"Kuyruk alınamadı");setRows(d.queue||[])}catch(e){setMsg(e.message)}}
 useEffect(()=>{load();fetch("/api/communication-send",{cache:"no-store"}).then(async r=>{if(!r.ok)throw Error("Gönderici bilgisi alınamadı");return r.json()}).then(d=>{setSender(d);setSent((d.recent||[]).map(x=>({name:x.name,email:x.recipients?.join(", "),id:x.id})))}).catch(e=>setMsg(e.message))},[]);
 return <><InboxManager/><section className="panel"><div className="section-title"><div><h2>İletişim Merkezi</h2><small>Doğrulanmış kanal ve sektöre uygun ilk temas mesajı</small></div><b>{rows.length} hazır</b></div>
 {msg&&<p className="client-message" role="status">{msg}</p>}
 <section aria-label="Saatlik otomatik iletişim"><h3>Saatlik otomatik iletişim</h3>
 <p>{automation?`${automation.policy.enabled?'Aktif':'Kapalı'} · Günlük en fazla ${automation.policy.dailyLimit}, tur başına ${automation.policy.perCycle} gönderim · Takip: 4 gün + 5 gün, en fazla 2`:'Durum yükleniyor…'}</p>
 <p>Önce tüm aday havuzu karşılaştırılır; uzmanlık, doğrudan sayfa kontrolleri ve doğrulanmış iletişime göre en güçlü 50 adaylık liste yenilenir. İlk temas ve takip aynı saatlik ve günlük kotayı paylaşır. Bunlar üst sınırlardır; uygun aday sayısı daha az olabilir.</p>
 {automation?.recent?.find(x=>x.report.selection?.evaluated>0)&&(()=>{const review=automation.recent.find(x=>x.report.selection?.evaluated>0).report.selection;return <section aria-label="Genel aday değerlendirmesi"><h4>Genel aday değerlendirmesi</h4><p>{review.evaluated} aday değerlendirildi · {review.qualified} iletişime uygun · {review.awaitingAnalysis} analiz bekliyor · {review.selected.length} öncelikli aday seçildi</p><ol>{review.selected.slice(0,10).map(x=><li key={x.id}><strong>{x.name}</strong> · Öncelik {x.priority}/100<small style={{display:'block'}}>{x.reasons.join(' · ')}</small></li>)}</ol><small>Öncelik puanı satış olasılığı değildir. Gönderimden önce resmî sayfa ve yanıt durumu tekrar kontrol edilir.</small></section>})()}
 <p>Resmî sayfada doğrulanan işletme adresleriyle ilk temas. Yanıt gelen veya iletişim istemeyen adreslerde takip durur. Creator aramaları ayrı devam eder.</p>
 <button disabled={autoBusy} onClick={()=>runAutomation(true)}>Gönderimsiz kontrol et</button>{' '}
 <button disabled={autoBusy||!automation?.policy?.enabled} onClick={()=>runAutomation(false)}>{autoBusy?'Kontrol ediliyor…':'Kontrollü iletişim turunu çalıştır'}</button>
 {automation?.recent?.map((x,i)=><p key={i}>{new Date(x.createdAt).toLocaleString('tr-TR')} · {x.report.dryRun?'Kontrol':'Tur'} · İlk temas {x.report.firstSent}, takip {x.report.followSent}, uygun {x.report.eligible}, hata {x.report.errors?.length||0} {x.report.deferred?`· ${x.report.deferred}`:''}</p>)}
 </section>
 <p>{sender?`Gönderici: ${sender.from||"Tanımlanmamış"}`:"Gönderici kontrol ediliyor…"}{sender&&!sender.configured?` · ${sender.reason}`:""}</p>
 {sent.map(x=><div role="status" key={x.id||x.email}><p>{x.name} · {x.email} · E-posta sağlayıcısı kabul etti · Kayıt: {x.id}. {deliveryEvents[x.id]?`Sağlayıcı olayı: ${deliveryEvents[x.id]}`:"Teslimat henüz doğrulanmadı."}</p><button onClick={()=>checkDelivery(x.id)}>Teslimatı kontrol et</button></div>)}
 {!rows.length?<div className="empty">Gönderime hazırlanmış doğrulanmış aday henüz yok.</div>:<div className="client-list">{rows.map(x=><article className="client-row" key={x.id}>
  <div className="client-avatar">✉</div><div><b>{x.name}</b><small>{x.city}, {x.country} · {x.qualificationLevel} {x.qualificationScore??"—"}/100</small><p style={{margin:"6px 0"}}>{x.outreachReason}</p><small>{x.contactEmail||x.contactUrl}</small></div>
  <div><b>{x.proposalPackage}</b><small>{x.proposalAmount} {x.proposalCurrency}</small><small>İç teklif taslağı; ihtiyaç ve kapsam doğrulaması bekler. İlk mesajda gönderilmez.</small></div>
  <details><summary>İlk temas mesajı</summary><p><strong>Konu: {x.outreachSubject}</strong></p><small>Yaklaşım: {({buyer:"Alıcı ve uzmanlık",local:"Yerel müşteri tercihi",product:"Ürün ve satın alma",discovery:"Keşif ve görünürlük"})[x.outreachApproach]}. Ücretsiz puan yeterli ölçümle gösterilir; ayrıntılı rapor ve takip ücretlidir.</small><p><a href={x.freeAssessmentUrl} target="_blank" rel="noopener noreferrer">Ücretsiz ön değerlendirmeyi aç ↗</a></p><textarea aria-label={`${x.name} mesajı`} rows={9} style={{width:"100%",minWidth:250,maxWidth:560}} value={x.outreachDraft} readOnly/></details>
  <div><button disabled={!!sending||!sender?.configured||!x.contactEmail} onClick={()=>send(x)}>{sending===x.id?"Gönderiliyor…":"İlk temas e-postasını gönder"}</button><small style={{display:"block"}}>{x.contactEmail?"Henüz gönderilmedi":"E-posta bulunamadı; iletişim sayfası mevcut"}</small></div>
 </article>)}</div>}</section></>
}
