"use client";
import {useEffect,useMemo,useRef,useState} from "react";

import {businessMetricSummary,commerceSignalSummary,readCommerceClient} from "../lib/commerce-impact-view";
import {accountScanEstimates} from "../lib/client-account-view";
import {provisionalScore} from "../lib/scan-workspace";
function clamp(n){return Math.max(0,Math.min(100,Math.round(Number(n)||0)))}
function level(score){if(score>=75)return "Güçlü";if(score>=50)return "Geliştirilmeli";return "Kritik"}
const blankSignals={catalogStatus:"unknown",catalogEvidence:"",pricingStatus:"unknown",pricingEvidence:"",availabilityStatus:"unknown",availabilityEvidence:"",purchasePathStatus:"unknown",purchasePathEvidence:""};
const blankMetrics={monthlyTraffic:"",monthlyConversions:"",averageValue:"",monthlyRevenue:"",currency:"TRY",evidence:""};
const signalDefs=[["catalogStatus","catalogEvidence","Ürün / hizmet kataloğu"],["pricingStatus","pricingEvidence","Fiyat / teklif netliği"],["availabilityStatus","availabilityEvidence","Stok / uygunluk"],["purchasePathStatus","purchasePathEvidence","Satın alma / rezervasyon yolu"]];

const statusLabel={unknown:"Bağlı değil",partial:"Kısmi",verified:"Kanıt notlu beyan"};
function money(v,currency){if(v===null||v===undefined||v==="")return "—";return Number(v).toLocaleString("tr-TR",{maximumFractionDigits:2})+" "+(currency||"TRY")}

export default function CommerceImpactManager(){
  const [clients,setClients]=useState([]),[scans,setScans]=useState([]),[findings,setFindings]=useState([]),[clientId,setClientId]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(""),[signals,setSignals]=useState(blankSignals),[signalBusy,setSignalBusy]=useState(false),[metrics,setMetrics]=useState(blankMetrics),[metricsBusy,setMetricsBusy]=useState(false),[loading,setLoading]=useState(true),[clientLoading,setClientLoading]=useState(true),[clientReady,setClientReady]=useState(false),[loadError,setLoadError]=useState(""),[revision,setRevision]=useState(0);
  const requestVersion=useRef(0);

  async function load(signal){
    const read=async(path,key)=>{const r=await fetch(path,{cache:"no-store",signal});if(!r.ok)throw Error("Commerce Ready kaynakları okunamadı.");const d=await r.json();if(!Array.isArray(d[key])||(key==="scans"&&d.mode!=="database"))throw Error("Commerce Ready kaynakları doğrulanamadı.");return d[key]};
    const [list,scanRows,findingRows]=await Promise.all([read("/api/clients","clients"),read("/api/scans","scans"),read("/api/findings","findings")]);
    if(signal?.aborted)return;
    setClients(list);setScans(scanRows);setFindings(findingRows);setClientId(prev=>list.some(x=>x.id===prev)?prev:list[0]?.id||"");
  }
  useEffect(()=>{
    const controller=new AbortController();let active=true;const timer=setTimeout(()=>controller.abort(),20000);
    setLoading(true);setLoadError("");
    load(controller.signal).catch(()=>{if(active){setClients([]);setScans([]);setFindings([]);setLoadError("Commerce Ready verileri alınamadı. Sonuçlar bilinmiyor.")}}).finally(()=>{clearTimeout(timer);if(active)setLoading(false)});
    return ()=>{active=false;clearTimeout(timer);controller.abort()};
  },[revision]);
  useEffect(()=>{
    const version=++requestVersion.current,controller=new AbortController();
    setSignals(blankSignals);setMetrics(blankMetrics);setClientReady(false);setClientLoading(Boolean(clientId));
    if(!clientId)return;
    const timer=setTimeout(()=>controller.abort(),20000);
    readCommerceClient(fetch,clientId,controller.signal).then(d=>{
      if(version!==requestVersion.current||controller.signal.aborted)return;
      setSignals({...blankSignals,...d.signals});setMetrics({...blankMetrics,...d.metrics,...Object.fromEntries(["monthlyTraffic","monthlyConversions","averageValue","monthlyRevenue"].map(k=>[k,d.metrics[k]??""]))});setClientReady(true);
    }).catch(()=>{if(version===requestVersion.current)setMsg("Seçilen işletmenin ticari kayıtları alınamadı. Sonuçlar bilinmiyor.")}).finally(()=>{clearTimeout(timer);if(version===requestVersion.current)setClientLoading(false)});
    return ()=>{++requestVersion.current;clearTimeout(timer);controller.abort()};
  },[clientId,revision]);

  async function setPriority(x,priority){setBusy(x.id);setMsg("");try{const r=await fetch("/api/findings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({findingId:x.id,offerId:x.offerId,priority})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Öncelik güncellenemedi.");setMsg(priority?"Aksiyon önceliklendirildi.":"Aksiyon öncelikten çıkarıldı.");await load()}catch(e){setMsg(e.message)}finally{setBusy("")}}
  async function saveSignals(){setSignalBusy(true);setMsg("");try{const r=await fetch("/api/commerce-signals",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({clientId,...signals})});const d=await r.json();if(!r.ok||d.signals?.clientId!==clientId)throw new Error("Ticari sinyaller kaydedilemedi.");setSignals({...blankSignals,...d.signals});setMsg("Ticari sinyal beyanları kaydedildi.")}catch(e){setMsg(e.message)}finally{setSignalBusy(false)}}
  async function saveMetrics(){setMetricsBusy(true);setMsg("");try{const r=await fetch("/api/business-impact",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({clientId,...metrics})});const d=await r.json();if(!r.ok||d.metrics?.clientId!==clientId)throw new Error("Business Impact verileri kaydedilemedi.");const m=d.metrics||{};setMetrics({...blankMetrics,...m,monthlyTraffic:m.monthlyTraffic??"",monthlyConversions:m.monthlyConversions??"",averageValue:m.averageValue??"",monthlyRevenue:m.monthlyRevenue??""});setMsg("Kaynak notlu işletme beyanı kaydedildi.")}catch(e){setMsg(e.message)}finally{setMetricsBusy(false)}}

  const client=useMemo(()=>clients.find(x=>x.id===clientId)||null,[clients,clientId]);
  const latest=useMemo(()=>accountScanEstimates(scans.filter(x=>x.clientId===clientId)).latest,[scans,clientId]);
  const clientFindings=useMemo(()=>findings.filter(x=>x.clientId===clientId),[findings,clientId]);
  const unresolved=clientFindings.filter(x=>!["resolved","dismissed"].includes(x.status));
  const critical=unresolved.filter(x=>x.severity==="critical").length,high=unresolved.filter(x=>x.severity==="high").length,requested=clientFindings.filter(x=>x.status==="requested"||x.offerStatus==="requested").length,prioritized=unresolved.filter(x=>x.priority).length;
  const p=client?.profile||{},profileFields=[p.country,p.city,p.sector,p.phone,p.contactEmail],profileScore=clamp((profileFields.filter(Boolean).length/profileFields.length)*100);
  const {score:readiness,covered:signalCoverage,declared:verifiedSignals}=commerceSignalSummary(signals);
  const weights={critical:4,high:3,medium:2,low:1},topActions=unresolved.slice().sort((a,b)=>Number(b.priority)-Number(a.priority)||(weights[b.severity]||0)-(weights[a.severity]||0)).slice(0,5);
  const {coverage:metricCoverage,conversionRate,recordedRevenue,derivedRevenue}=businessMetricSummary(metrics);

  if(loading)return <section className="panel"><p>Commerce Ready verileri yükleniyor…</p></section>;
  if(loadError)return <section className="panel"><p role="status">{loadError}</p><button onClick={()=>setRevision(v=>v+1)}>Yeniden yükle</button></section>;
  if(!clients.length)return <section className="panel"><p>Henüz işletme kaydı yok.</p></section>;
  return <section className="grid reports-grid">
    <article className="panel" style={{gridColumn:"1/-1"}}><div className="section-title"><div><h2>Commerce Ready + Business Impact</h2><small>Ticari hazırlık beyanları ve kaynak notlu işletme verileri. AI görünürlük veya gelir artışı ölçümü değildir.</small></div></div><label className="report-select">Müşteri<select value={clientId} disabled={Boolean(busy)||signalBusy||metricsBusy} onChange={e=>{setClientReady(false);setSignals(blankSignals);setMetrics(blankMetrics);setClientId(e.target.value);setMsg("")}}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{msg&&<p className="client-message">{msg}</p>}</article>

    {clientLoading?<article className="panel"><p>Ticari kayıtlar yükleniyor…</p></article>:!clientReady?<article className="panel"><p>Ticari sonuçlar bilinmiyor.</p><button onClick={()=>setRevision(v=>v+1)}>Yeniden yükle</button></article>:<>
    <article className="panel"><div className="report-heading"><h2>Commerce Ready</h2><small>Kaynak notlu yönetici beyanları</small></div><div className="report-kpis"><div><span>Beyanlara göre hazırlık</span><strong>{readiness===null?"—":readiness+"/100"}</strong></div><div><span>Durum</span><strong>{readiness===null?"Kapsam eksik":level(readiness)}</strong></div><div><span>Kanıt notlu beyan</span><strong>{verifiedSignals}/4</strong></div></div><div className="content-ideas" style={{marginTop:14}}><div><strong>Tarama ön puanı</strong><small>{latest?provisionalScore(latest.score):"Tamamlanmış tarama yok"}</small></div><div><strong>İşletme veri bütünlüğü</strong><small>{profileScore}/100 · ülke, şehir, sektör, telefon, e-posta</small></div><div><strong>Açık bulgu</strong><small>{unresolved.length} kayıt · yokluğu hazırlık kanıtı değildir</small></div><div><strong>Ticari sinyal kapsamı</strong><small>{signalCoverage}/4 alan · skor için dört alanın kaynak notu gerekir</small></div></div></article>

    <article className="panel"><div className="report-heading"><h2>Ticari sinyal kaydı</h2><small>Kanıt notu bağımsız doğrulama değildir</small></div><div className="client-list">{signalDefs.map(([statusKey,evidenceKey,label])=><div className="client-row" key={statusKey} style={{display:"grid",gridTemplateColumns:"minmax(0,1fr)",gap:8}}><div><b>{label}</b><small>{statusLabel[signals[statusKey]]||"Bağlı değil"}</small></div><select value={signals[statusKey]} onChange={e=>setSignals(s=>({...s,[statusKey]:e.target.value}))}><option value="unknown">Bağlı değil</option><option value="partial">Kısmi</option><option value="verified">Kanıt notlu beyan</option></select><textarea value={signals[evidenceKey]||""} onChange={e=>setSignals(s=>({...s,[evidenceKey]:e.target.value}))} placeholder="Kanıt / kaynak notu yazın (URL, sistem, dosya vb.)" rows={2} style={{width:"100%",minHeight:54,resize:"vertical",padding:"10px 12px",borderRadius:10,boxSizing:"border-box",fontSize:16}} /></div>)}</div><button type="button" onClick={saveSignals} disabled={signalBusy||metricsBusy||!clientId||!clientReady} style={{width:"auto",marginTop:12,minHeight:42,padding:"10px 16px"}}>{signalBusy?"Kaydediliyor…":"Ticari sinyalleri kaydet"}</button><p style={{marginBottom:0,marginTop:10}}><small>Dört alanın tamamında kaynak notu bulunmadan hazırlık puanı gösterilmez. Bu kayıtlar AI alışveriş ajanıyla yapılmış test değildir.</small></p></article>

    <article className="panel"><div className="report-heading"><h2>Business Impact</h2><small>İşletme beyanından hesaplanan göstergeler</small></div><div className="report-kpis"><div><span>Kritik açık bulgu</span><strong>{critical}</strong></div><div><span>Yüksek öncelikli bulgu</span><strong>{high}</strong></div><div><span>Veri kapsamı</span><strong>{metricCoverage}/4</strong></div></div><div className="content-ideas" style={{marginTop:14}}><div><strong>Talep edilen çözüm</strong><small>{requested} kayıt</small></div><div><strong>Öncelikli aksiyon</strong><small>{prioritized} kayıt</small></div><div><strong>Dönüşüm oranı</strong><small>{conversionRate===null?"Gerçek veri bekleniyor":conversionRate.toFixed(2)+"%"}</small></div><div><strong>Kaynak notlu aylık gelir beyanı</strong><small>{recordedRevenue!==null?money(recordedRevenue,metrics.currency):"Kaynak notlu gelir kaydı bekleniyor"}</small></div><div><strong>Hesaplanan ciro tahmini</strong><small>{derivedRevenue===null?"Veri / kaynak bekleniyor":money(derivedRevenue,metrics.currency)+" · dönüşüm × ortalama değer"}</small></div></div><p><small>Bu göstergeler sistemin ürettiği ek gelir, net kâr veya ROI değildir. Alanlar aynı döneme ait olmalıdır.</small></p></article>

    <article className="panel"><div className="report-heading"><h2>Kaynak notlu ticari veri</h2><small>Kaynak gösterilmeden parasal etki üretilmez</small></div><div className="client-list"><label className="client-row" style={{display:"grid",gap:6}}><b>Aylık trafik / ziyaret</b><input inputMode="numeric" value={metrics.monthlyTraffic} onChange={e=>setMetrics(m=>({...m,monthlyTraffic:e.target.value}))} placeholder="Örn. 12000" /></label><label className="client-row" style={{display:"grid",gap:6}}><b>Aylık dönüşüm / rezervasyon / satış</b><input inputMode="numeric" value={metrics.monthlyConversions} onChange={e=>setMetrics(m=>({...m,monthlyConversions:e.target.value}))} placeholder="Örn. 240" /></label><label className="client-row" style={{display:"grid",gap:6}}><b>Ortalama sepet / rezervasyon değeri</b><input inputMode="decimal" value={metrics.averageValue} onChange={e=>setMetrics(m=>({...m,averageValue:e.target.value}))} placeholder="Örn. 1850" /></label><label className="client-row" style={{display:"grid",gap:6}}><b>Aylık gerçekleşen gelir</b><input inputMode="decimal" value={metrics.monthlyRevenue} onChange={e=>setMetrics(m=>({...m,monthlyRevenue:e.target.value}))} placeholder="Varsa gerçek değer" /></label><label className="client-row" style={{display:"grid",gap:6}}><b>Para birimi</b><select value={metrics.currency||"TRY"} onChange={e=>setMetrics(m=>({...m,currency:e.target.value}))}><option value="TRY">TRY</option><option value="USD">USD</option><option value="EUR">EUR</option><option value="GBP">GBP</option></select></label><label className="client-row" style={{display:"grid",gap:6}}><b>Kanıt / veri kaynağı</b><textarea rows={2} value={metrics.evidence||""} onChange={e=>setMetrics(m=>({...m,evidence:e.target.value}))} placeholder="GA4, CRM, rezervasyon sistemi, satış raporu vb." style={{width:"100%",minHeight:54,padding:"10px 12px",borderRadius:10,boxSizing:"border-box",fontSize:16}} /></label></div><button type="button" onClick={saveMetrics} disabled={metricsBusy||signalBusy||!clientId||!clientReady} style={{width:"auto",marginTop:12,minHeight:42,padding:"10px 16px"}}>{metricsBusy?"Kaydediliyor…":"Ticari veri beyanını kaydet"}</button><p style={{marginBottom:0,marginTop:10}}><small>Boş alanlar sıfır sayılmaz. Hesaplama için kaynak notu gerekir; elle girilen bilgiler bağımsız doğrulama değildir.</small></p></article>

    <article className="panel" style={{gridColumn:"1/-1"}}><div className="section-title"><div><h2>Öncelikli ticari aksiyonlar</h2><small>Öncelik verilen kayıtlar üstte tutulur; seçim veritabanına kaydedilir.</small></div></div>{!topActions.length?<div className="empty">Bu müşteri için açık aksiyon bulunmuyor.</div>:<div className="client-list">{topActions.map(x=><div className="client-row" key={x.id} style={{alignItems:"center",gap:12}}><div style={{minWidth:0,flex:1}}><b>{x.title}</b><small>{x.severity==="critical"?"Kritik":x.severity==="high"?"Yüksek":x.severity==="medium"?"Orta":"Düşük"} · {x.status==="requested"?"Talep edildi":x.status}{x.priority?" · Öncelikli":""}</small>{x.solutionTitle&&<small>{x.solutionTitle}</small>}</div><div style={{display:"flex",alignItems:"center",gap:8,flex:"0 0 auto",flexWrap:"wrap",justifyContent:"flex-end"}}>{x.price>0&&<span>{Number(x.price).toLocaleString("tr-TR")} {x.currency||"TL"}</span>}<button type="button" disabled={Boolean(busy)||signalBusy||metricsBusy} onClick={()=>setPriority(x,!x.priority)} style={{width:"auto",minWidth:118,padding:"10px 14px",minHeight:42}}>{busy===x.id?"Kaydediliyor…":x.priority?"Öncelikten çıkar":"Önceliklendir"}</button></div></div>)}</div>}</article>
    </>}
  </section>;
}
