"use client";
import {useEffect,useRef,useState} from 'react';
import {readDashboardEvidence} from '../lib/dashboard-evidence.js';
export default function DashboardAnswerEvidence(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),version=useRef(0),controller=useRef(null);
 async function load(){const current=++version.current;controller.current?.abort();const c=new AbortController();controller.current=c;const timeout=setTimeout(()=>c.abort(),15000);setLoading(true);try{const r=await fetch('/api/answer-evidence/daily',{cache:'no-store',signal:c.signal});if(!r.ok)throw Error('unavailable');const next=readDashboardEvidence(await r.json());if(current===version.current){setData(next);setError('')}}catch{if(current===version.current){setData(null);setError('AI yanıt ölçümleri alınamadı; sayımlar bilinmiyor.')}}finally{clearTimeout(timeout);if(current===version.current)setLoading(false)}}
 useEffect(()=>{load();const timer=setInterval(load,60000);return()=>{version.current++;controller.current?.abort();clearInterval(timer)}},[]);
 const cards=data?[['Ölçüm turu',data.counts.runs],['Nötr ve tam AI yanıtı',data.counts.neutralComplete],['Marka adı bulunan yanıt',data.counts.brandMentions],['Resmî kaynak atfı bulunan yanıt',data.counts.officialCitations],['Başarısız çağrı',data.counts.failed]]:[];
 return <section className="mv-card"><div className="mv-title"><h2>Gerçek AI yanıt örnekleri</h2><a href="/yanit-kanitlari">Yanıt kanıtlarını aç →</a></div><button type="button" onClick={load} disabled={loading}>{loading?'Ölçümler yükleniyor…':'Ölçümleri yenile'}</button>{error?<p role="alert">{error}</p>:!data?<p role="status">Ölçüm kayıtları bekleniyor…</p>:<><p>{data.date.split('-').reverse().join('.')} · Türkiye saatiyle günün kayıtları. Son yükleme: {new Date(data.generatedAt).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})}{loading?' · Yeni yükleme bekleniyor; önceki kayıtlar gösteriliyor.':''}</p><dl style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:14}}>{cards.map(([label,n])=><div key={label}><dt style={{fontSize:13,color:'#8ea6b4'}}>{label}</dt><dd style={{margin:0,fontWeight:800,fontSize:26}}>{n}</dd></div>)}</dl>{data.limited&&<p>Bu günün toplam {data.totalRuns} turundan en yeni 1000 tur özetlendi.</p>}<p style={{fontSize:13,color:'#8ea6b4'}}>Bu sayılar farklı işletme ve sorgulardaki kaydedilmiş API yanıt örnekleridir; genel görünürlük skoru veya çözümün etkisi değildir. Marka adı ya da alan adı sorguda verilen ve eksik dönen yanıtlar eşleşme sayılarına katılmaz. Başarısız çağrı, markanın görünmediği anlamına gelmez.</p>{data.counts.runs===0&&<p>Bu gün için kayıtlı ölçüm turu yok; görünürlük durumu bilinmiyor.</p>}</>}</section>;
}
