"use client";
import {useEffect,useRef,useState} from "react";

const number=value=>Number(value||0).toLocaleString("tr-TR");
export default function ExecutiveDailyReport(){
 const [d,setD]=useState(null),[err,setErr]=useState(""),[closed,setClosed]=useState(false),[loading,setLoading]=useState(false);
 const reopen=useRef(null),closeButton=useRef(null);
 async function load(){
  setErr("");setLoading(true);
  try{const r=await fetch("/api/executive-daily-report",{cache:"no-store"});const x=await r.json();if(!r.ok||x.error)throw new Error(x.error||"Rapor yüklenemedi.");setD(x)}
  catch(e){setErr(e.message)}finally{setLoading(false)}
 }
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(closed)reopen.current?.focus()},[closed]);
 function open(){setClosed(false);requestAnimationFrame(()=>closeButton.current?.focus())}
 if(closed)return <section className="panel" style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><span>Yönetici raporu kapatıldı.</span><button ref={reopen} onClick={open}>Günlük Raporu Aç</button></section>;
 const f=d?.funnel||{},p=f.prospects||{},pay=f.payments||{},work=f.work||{},re=f.remeasurement||{};
 const cards=[["Bulunan aday",p.total],["Nitelikli aday",p.qualified],["Temas",p.contacted],["Cevap",p.replies],["Teklif",p.proposals],["Satış",p.won],["Ödeme adedi",pay.paid],["Gelir",pay.revenue],["Tamamlanan çözüm",work.completed],["Bloke iş",work.blocked],["İyileşen",re.improved],["Ort. skor değişimi",Number(re.avgDelta||0).toFixed(1)]];
 const rates=[["Nitelikli aday",d?.conversion?.qualifiedRate],["Temasa cevap",d?.conversion?.replyRate],["Tekliften satış",d?.conversion?.winRate]];
 const tags=(items,empty)=>items?.length?<div className="er-tags">{items.map((x,i)=><span key={i}>{x}</span>)}</div>:<p className="er-muted">{empty}</p>;
 return <section className="executive-daily-report" aria-labelledby="executive-report-title">
  <div className="executive-report-controls er-toolbar"><span>YÖNETİCİ RAPORU</span><div><button onClick={load} disabled={loading}>{loading?"Yükleniyor…":"Yenile"}</button><button className="er-print" onClick={()=>window.print()} disabled={!d||!!err}>Yazdır / PDF</button><button ref={closeButton} className="er-close" onClick={()=>setClosed(true)} aria-label="Yönetici raporunu kapat" title="Raporu kapat">×</button></div></div>
  <header className="er-letterhead"><div className="er-brand"><div className="er-monogram" aria-hidden="true">AV<span>●</span></div><div><strong>AI VISIBILITY</strong><small>Digital Visibility Intelligence Platform</small></div></div><div className="er-confidential">YÖNETİCİYE ÖZEL<span>GİZLİ RAPOR</span></div></header>
  <div className="er-title"><div><span className="er-eyebrow">GÜNLÜK FAALİYET / YÖNETİCİ ÖZETİ</span><h1 id="executive-report-title">Günün resmi.<br/><span>Yarının öncelikleri.</span></h1><p>Business · Creator · Ajan Amirleri</p></div><div className="er-date"><small>RAPOR TARİHİ</small><b>{d?.date?d.date.split("-").reverse().join("."):"—"}</b><small>Günlük faaliyet + genel dönüşüm</small></div></div>
  {err?<div className="er-error" role="alert"><b>Rapor yüklenemedi</b><p>{err}</p><button onClick={load} disabled={loading}>Yeniden Dene</button></div>:!d?<p role="status">Rapor hazırlanıyor…</p>:<>
  <div className="er-summary"><article><span className="er-step">01 / FAALİYET</span><h2>Bugün ne yaptık?</h2><div className="er-big">{number(d.totals?.discovered)}<small>işletme adayı</small></div><p>{number(d.creator?.found)} creator adayı işlendi; {number(d.totals?.completed)} derin analiz tamamlandı.</p></article><article><span className="er-step">02 / SONUÇ</span><h2>Genel dönüşüm</h2><div className="er-big">{number(p.won)}<small>satış</small></div><p>{number(p.qualified)} nitelikli aday · {number(p.proposals)} teklif · {number(pay.paid)} ödeme.</p></article><article><span className="er-step">03 / ÖNCELİK</span><h2>Yarın odağımız</h2><div className="er-big">{number(d.nextBestActions?.length)}<small>bekleyen aksiyon</small></div><p>{d.nextBestActions?.length?"Bekleyen aksiyonları öncelik sırasıyla değerlendirin.":"HOT adaylar, derin analiz ve satışa dönüşüm."}</p></article></div>
  <div className="er-section-title"><span>01</span><h2>Performans göstergeleri</h2><small>Genel durum</small></div>
  <div className="er-metrics">{cards.map(([k,v])=><div key={k}><span>{k}</span><strong>{k==="Ort. skor değişimi"?v:number(v)}</strong></div>)}</div>
  <div className="er-two-columns"><article><div className="er-section-title"><span>02</span><h2>Günün özeti</h2></div><p>{number(d.totals?.discovered)} işletme adayı bulundu, {number(d.creator?.found)} creator adayı işlendi ve {number(d.totals?.completed)} derin analiz tamamlandı.</p><div className="er-note">Yüksek fırsatlı creator: <b>{number(d.creator?.highOpportunity)}</b><br/>Kaydedilen hata: <b>{number(d.totals?.errors)}</b></div></article><article><div className="er-section-title"><span>03</span><h2>Dönüşüm oranları</h2></div>{rates.map(([label,v])=><div className="er-rate" key={label}><div><span>{label}</span><b>%{number(v)}</b></div><div className="er-track" aria-hidden="true"><span style={{width:`${Math.max(0,Math.min(100,Number(v)||0))}%`}}/></div></div>)}</article></div>
  <div className="er-section-title"><span>04</span><h2>Riskler ve bekleyen işler</h2></div>
  {d.risks?.length?<div className="er-risks">{d.risks.slice(0,8).map((x,i)=><div key={x.clientId||i}><strong>{x.name}</strong><span>{x.blocked} iş erişim veya onay bekliyor.</span></div>)}</div>:<div className="er-clear">✓ Aktif uygulama blokajı yok.</div>}
  <div className="er-two-columns er-context"><article><h3>Av bölgeleri</h3>{tags((d.markets||[]).map(x=>[x?.country,x?.city].filter(Boolean).join(" / ")).filter(Boolean),"Henüz bölge kaydı yok.")}</article><article><h3>Creator platformları</h3>{tags(d.creator?.platforms,"Henüz platform kaydı yok.")}</article></div>
  <div className="er-context"><h3>Çalışan ajanlar ve amirler</h3>{tags(d.agents,"Henüz ajan hareketi yok.")}</div>
  <div className="er-section-title"><span>05</span><h2>Son ajan hareketleri</h2></div>
  <div className="er-timeline">{d.events?.length?d.events.slice(0,12).map((x,i)=><article key={x.id||i}><span className="er-dot"/><div><small>{x.agent}</small><h3>{x.title}</h3><p>{x.detail}</p></div></article>):<p className="er-muted">Bugün için kayıtlı ajan hareketi bulunmuyor.</p>}</div>
  </>}
  <footer className="er-footer"><div><b>AI VISIBILITY</b><span>Yönetici Günlük Faaliyet Raporu</span></div><span>{d?.generatedAt?`Oluşturma: ${new Date(d.generatedAt).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul"})}`:""}</span></footer>
  <style>{`
  .executive-daily-report{width:100%;max-width:980px;margin:0 auto;padding:28px 36px;background:#fff;color:#172c40;border:1px solid #dce5eb;border-radius:20px;box-shadow:0 18px 60px #102f4210;font-family:Arial,sans-serif;box-sizing:border-box}
  .executive-daily-report *{box-sizing:border-box}.executive-daily-report p{line-height:1.65;font-size:14px}.er-toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:26px}.er-toolbar>span{font-size:10px;font-weight:700;letter-spacing:2px;color:#687d8e}.er-toolbar>div{display:flex;align-items:center;gap:8px}.executive-daily-report button{background:#f1f5f8;color:#183247;border:1px solid #d9e3e9;border-radius:9px;padding:9px 13px;font-size:12px;cursor:pointer}.executive-daily-report button:focus-visible{outline:3px solid #18a999;outline-offset:3px}.executive-daily-report button:disabled{opacity:.5;cursor:wait}.executive-daily-report .er-print{background:#16394c;color:white}.executive-daily-report .er-close{width:42px;height:42px;padding:0;font-size:28px;line-height:1;background:white;color:#365065}
  .er-letterhead{display:flex;justify-content:space-between;gap:18px;align-items:center;padding-bottom:22px;border-bottom:3px solid #16877e}.er-brand{display:flex;gap:12px;align-items:center}.er-monogram{position:relative;display:grid;place-items:center;background:#143448;color:white;width:52px;height:52px;border-radius:13px;font-size:21px;font-weight:800;letter-spacing:-2px}.er-monogram span{position:absolute;right:6px;bottom:3px;font-size:12px;color:#42d3b4;letter-spacing:0}.er-brand strong{display:block;letter-spacing:3px;font-size:16px}.er-brand small{display:block;font-size:10px;margin-top:6px;color:#657a8d}.er-confidential{text-align:right;font-size:9px;letter-spacing:1.5px;color:#6d7f8d}.er-confidential span{display:block;margin-top:7px;font-size:10px;color:#13786f;font-weight:bold}
  .er-title{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:30px 0}.er-eyebrow{font-size:10px;font-weight:bold;letter-spacing:1.5px;color:#167e77}.er-title h1{font-size:34px;line-height:1.15;letter-spacing:-1px;margin:12px 0}.er-title h1 span{color:#167e77}.er-title p{color:#718493;margin:0;font-size:12px}.er-date{border-left:1px solid #dce5eb;padding-left:22px;min-width:160px}.er-date small{display:block;font-size:9px;color:#6b7f90;line-height:1.6}.er-date b{display:block;font-size:23px;margin:7px 0}
  .er-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.er-summary article{padding:20px;border:1px solid #dce5eb;border-radius:12px;background:#f5f9fb}.er-summary article:last-child{background:#edf7f4;border-color:#c9e6df}.er-step{font-size:9px;letter-spacing:1.2px;color:#5e798c;font-weight:bold}.er-summary h2{font-size:15px;margin:12px 0}.er-big{font-size:34px;font-weight:800;letter-spacing:-1px}.er-big small{display:block;font-size:10px;font-weight:normal;letter-spacing:0;color:#6a7e8d;margin-top:3px}.er-summary p{font-size:12px;margin-bottom:0;color:#536e80}
  .er-section-title{display:flex;align-items:center;gap:10px;margin:28px 0 14px}.er-section-title>span{color:#16877e;font-size:11px;font-weight:bold}.er-section-title h2{font-size:16px;margin:0;letter-spacing:-.3px}.er-section-title>small{margin-left:auto;color:#738695;font-size:10px}.er-metrics{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid #dce5eb;border-radius:12px;overflow:hidden}.er-metrics>div{padding:15px;border-bottom:1px solid #e6edf1;border-right:1px solid #e6edf1}.er-metrics span{display:block;font-size:10px;color:#688093}.er-metrics strong{display:block;font-size:24px;margin-top:8px;font-variant-numeric:tabular-nums}
  .er-two-columns{display:grid;grid-template-columns:1fr 1fr;gap:28px}.er-note{padding:12px 15px;border-left:3px solid #16877e;background:#f3f8fa;font-size:12px;line-height:1.9}.er-rate{margin:15px 0}.er-rate>div:first-child{display:flex;justify-content:space-between;font-size:12px;margin-bottom:8px}.er-track{height:6px;border-radius:6px;background:#e8eff3;overflow:hidden}.er-track span{display:block;height:100%;background:#16877e;border-radius:6px}.er-clear{padding:14px;border:1px solid #cee6df;border-radius:10px;background:#f0f8f4;color:#176759;font-size:13px}.er-risks>div{display:flex;justify-content:space-between;gap:15px;padding:13px 0;border-bottom:1px solid #e5ebef;font-size:12px}.er-risks span{color:#956224}.er-context{margin-top:24px}.er-context h3{font-size:13px;margin:0 0 12px}.er-tags{display:flex;flex-wrap:wrap;gap:7px}.er-tags>span{padding:6px 10px;border:1px solid #dce5eb;border-radius:6px;background:#f8fafb;font-size:11px}.er-muted{color:#758898;font-size:12px}
  .er-timeline article{position:relative;display:flex;gap:14px;padding:0 0 18px;margin-left:5px;border-left:1px solid #dce5eb}.er-dot{flex-shrink:0;width:9px;height:9px;border:2px solid #16877e;border-radius:50%;background:white;margin-left:-5px;margin-top:4px}.er-timeline small{font-size:9px;color:#16877e;font-weight:bold;text-transform:uppercase;letter-spacing:.7px}.er-timeline h3{font-size:13px;margin:6px 0}.er-timeline p{font-size:12px;color:#6a8092;margin:0}.er-footer{display:flex;justify-content:space-between;gap:16px;align-items:center;border-top:2px solid #16394c;margin-top:28px;padding-top:16px;font-size:9px;color:#728695}.er-footer b{display:block;color:#183247;letter-spacing:2px;margin-bottom:5px}.er-footer span{display:block}.er-error{padding:20px;background:#fff5ef;border:1px solid #eed9c8;border-radius:12px}
  @media(max-width:640px){.executive-daily-report{padding:18px;border-radius:14px}.er-toolbar{flex-wrap:wrap}.er-letterhead{align-items:flex-start}.er-confidential{font-size:8px}.er-brand strong{font-size:12px;letter-spacing:2px}.er-brand small{font-size:8px;max-width:140px}.er-monogram{width:42px;height:42px}.er-title{display:block;padding:24px 0}.er-title h1{font-size:29px}.er-date{border-left:0;border-top:1px solid #dce5eb;padding:12px 0 0;margin-top:18px}.er-date b{font-size:19px}.er-summary{grid-template-columns:1fr}.er-summary article{padding:16px}.er-metrics{grid-template-columns:repeat(2,1fr)}.er-two-columns{grid-template-columns:1fr;gap:0}.er-risks>div{flex-direction:column;gap:6px}.er-footer{align-items:flex-start;flex-direction:column}.er-section-title h2{font-size:14px}}
  @media print{@page{size:A4;margin:14mm}body:has(.executive-daily-report) *{visibility:hidden}body .executive-daily-report,body .executive-daily-report *{visibility:visible}body .executive-daily-report{position:absolute;left:0;top:0;width:100%;max-width:none!important;margin:0!important;padding:0!important;border:0!important;border-radius:0!important;box-shadow:none!important;background:white!important;color:#172c40!important;print-color-adjust:exact;-webkit-print-color-adjust:exact}body .executive-report-controls{display:none!important}.er-title{display:flex;padding:20px 0}.er-title h1{font-size:28px}.er-date{border-top:0;border-left:1px solid #dce5eb;padding-left:20px;margin:0}.er-summary{grid-template-columns:repeat(3,1fr)}.er-summary article{padding:14px;break-inside:avoid}.er-metrics{grid-template-columns:repeat(4,1fr)}.er-metrics>div{padding:10px;break-inside:avoid}.er-metrics strong{font-size:20px}.er-two-columns{grid-template-columns:1fr 1fr;gap:22px}.er-section-title{margin-top:22px;break-after:avoid}.er-timeline article,.er-risks>div,.er-clear{break-inside:avoid}.er-footer{flex-direction:row}.executive-daily-report p{orphans:3;widows:3}}
  `}</style>
 </section>
}
