"use client";
import {useEffect,useState} from "react";
export default function ExecutiveDailyReport(){
 const [d,setD]=useState(null),[err,setErr]=useState("");
 const load=()=>{setErr("");return fetch("/api/executive-daily-report",{cache:"no-store"}).then(r=>r.json()).then(x=>{if(x.error)throw new Error(x.error);setD(x)}).catch(e=>setErr(e.message));};
 useEffect(()=>{load()},[]);
 if(err)return <section className="panel"><h3>Gün Sonu Yönetici Raporu</h3><p role="alert">{err}</p><button onClick={load}>Yeniden Dene</button></section>;
 if(!d)return <section className="panel"><h3>Gün Sonu Yönetici Raporu</h3><p>Rapor hazırlanıyor…</p></section>;
 const f=d.funnel||{},p=f.prospects||{},pay=f.payments||{},work=f.work||{},re=f.remeasurement||{};
 const cards=[["Bulunan aday",p.total||0],["Nitelikli",p.qualified||0],["Temas",p.contacted||0],["Cevap",p.replies||0],["Teklif",p.proposals||0],["Satış",p.won||0],["Ödenen",pay.paid||0],["Gelir",Number(pay.revenue||0).toLocaleString("tr-TR")],["Çözüm tamamlandı",work.completed||0],["Bloke iş",work.blocked||0],["İyileşen",re.improved||0],["Ort. skor değişimi",Number(re.avgDelta||0).toFixed(1)]];
 return <section className="panel executive-daily-report" style={{background:"#fff",color:"#0f172a",maxWidth:900,margin:"0 auto",padding:24}}><div style={{borderBottom:"3px solid #0f766e",paddingBottom:14,marginBottom:18}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start",flexWrap:"wrap"}}><div><div style={{fontSize:13,fontWeight:900,letterSpacing:2}}>AI VISIBILITY</div><h1 style={{margin:"5px 0 4px"}}>Günlük Yönetici Faaliyet Raporu</h1><div style={{opacity:.7}}>YÖNETİCİYE ÖZEL · GİZLİ · {d.date}</div></div><div style={{textAlign:"right"}}><b>Digital Visibility Intelligence Platform</b><div style={{fontSize:13,opacity:.7}}>Business + Creator + Ajan Amirleri</div></div></div></div><div className="executive-report-controls" style={{display:"flex",gap:8,justifyContent:"flex-end",flexWrap:"wrap"}}><button onClick={load}>Yenile</button><button onClick={()=>window.print()}>Antetli Raporu Yazdır / PDF</button></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:10,marginTop:16}}><div style={{padding:14,border:"1px solid #cbd5e1",borderRadius:14}}><b>Bugün Ne Yaptık?</b><p style={{marginBottom:0}}>{d.totals?.discovered||0} işletme ve {d.creator?.found||0} creator adayı işlendi; {d.totals?.completed||0} derin analiz tamamlandı.</p></div><div style={{padding:14,border:"1px solid #cbd5e1",borderRadius:14}}><b>Genel Dönüşüm Durumu</b><p style={{marginBottom:0}}>{p.qualified||0} nitelikli aday · {p.proposals||0} teklif · {p.won||0} satış · {pay.paid||0} ödeme.</p></div><div style={{padding:14,border:"1px solid #cbd5e1",borderRadius:14}}><b>Yarın Öncelik</b><p style={{marginBottom:0}}>{d.nextBestActions?.length?`${d.nextBestActions.length} öncelikli aksiyon bekliyor.`:"HOT adaylar, derin analiz ve satışa dönüşüm öncelikli."}</p></div></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:10,marginTop:14}}>{cards.map(([k,v])=><div key={k} style={{padding:12,border:"1px solid rgba(148,163,184,.22)",borderRadius:14}}><small style={{opacity:.7}}>{k}</small><h2 style={{margin:"5px 0 0"}}>{v}</h2></div>)}</div>
 <h3>Günün Yönetici Özeti</h3><p>Bugün {d.totals?.discovered||0} işletme adayı bulundu, {d.creator?.found||0} creator adayı işlendi, {d.totals?.completed||0} derin analiz tamamlandı ve {d.totals?.errors||0} hata kaydedildi. Yüksek fırsatlı creator sayısı {d.creator?.highOpportunity||0}.</p><h3>Dönüşüm Hunisi · Genel Durum</h3><p>Nitelik %{d.conversion?.qualifiedRate||0} · Cevap %{d.conversion?.replyRate||0} · Tekliften satış %{d.conversion?.winRate||0}</p>
 <h3>Öngörülen Riskler</h3>{d.risks?.length?d.risks.slice(0,8).map(x=><div key={x.clientId} style={{padding:"8px 0",borderTop:"1px solid rgba(148,163,184,.15)"}}><strong>{x.name}</strong> — {x.blocked} iş erişim/onay bekliyor.</div>):<p>Aktif uygulama blokajı yok.</p>}
 <h3>Av Bölgeleri</h3><p>{d.markets.length?d.markets.map(x=>[x.country,x.city].filter(Boolean).join(" / ")).join(" · "):"Henüz kayıt yok."}</p>
 <h3>Creator Platformları</h3><p>{d.creator.platforms.length?d.creator.platforms.join(" · "):"Henüz kayıt yok."}</p>
 <h3>Çalışan Ajan / Amirler</h3><p>{d.agents.length?d.agents.join(" · "):"Henüz kayıt yok."}</p>
 <h3>Son Ajan Hareketleri</h3>{d.events.slice(0,12).map(x=><div key={x.id} style={{padding:"9px 0",borderTop:"1px solid rgba(148,163,184,.15)"}}><strong>{x.agent}</strong> — {x.title}<div style={{fontSize:13,opacity:.68}}>{x.detail}</div></div>)}
 <style>{`@media print { @page { size: A4; margin: 14mm; } body:has(.executive-daily-report) * { visibility: hidden; } body .executive-daily-report, body .executive-daily-report * { visibility: visible; } body .executive-daily-report { position: absolute; left: 0; top: 0; width: 100%; max-width: none !important; margin: 0 !important; padding: 0 !important; border: 0 !important; box-shadow: none !important; background: white !important; color: #0f172a !important; } body .executive-report-controls { display: none !important; } .executive-daily-report h3 { break-after: avoid; } .executive-daily-report p { orphans: 3; widows: 3; } }`}</style><div style={{marginTop:28,paddingTop:14,borderTop:"1px solid #cbd5e1",display:"flex",justifyContent:"space-between",gap:12,fontSize:12,opacity:.7}}><span>AI Visibility · Yönetici Günlük Raporu</span><span>Oluşturma: {new Date(d.generatedAt).toLocaleString("tr-TR")}</span></div></section>
}
