"use client";
import {useEffect,useState} from 'react';
const labels={queued:'İşlem bekliyor','awaiting-review':'İnceleyici değerlendirmesi bekliyor',analyzed:'Analiz edildi','review-required':'İnsan incelemesi gerekiyor'};
function InboxReviewTransfer({onSaved}){
 const [batch,setBatch]=useState(null),[text,setText]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function exportBatch(){setBusy(true);try{const r=await fetch('/api/inbox-review',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setBatch(d);setNotice(`${d.pending} yanıt değerlendirme bekliyor; ${d.messages.length} yanıt bu grupta. ${d.verificationRequired} kayıt gönderici kontrolü bekliyor.`)}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 async function importBatch(){setBusy(true);try{const r=await fetch('/api/inbox-review',{method:'POST',headers:{'content-type':'application/json'},body:text}),d=await r.json();if(!r.ok)throw Error(d.error);setNotice(`${d.results.filter(x=>x.status==='saved').length} değerlendirme kaydedildi; ${d.results.filter(x=>x.status!=='saved').length} kaydedilemedi. Ücretli AI çağrısı ve e-posta gönderimi yapılmadı.`);setBatch(null);await onSaved()}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 return <section aria-label="Yanıt değerlendirme aktarımı"><h3>Yanıt değerlendirme aktarımı</h3><p>Doğrulanmış yanıtları 10 kayıtlık gruplarla burada inceleyip özet, cevap taslağı ve sonraki işlemi sisteme aktarın. Her değerlendirme özgün e-postaya ve kayıt sürümüne bağlanır. Gönderici kontrolü bekleyen kayıtlar bu akışa alınmaz.</p><button disabled={busy} onClick={exportBatch}>İnceleme bekleyen 10 yanıtı göster</button>{batch&&<details open><summary>Yanıt inceleme grubu</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(batch,null,2)}</pre></details>}<details><summary>Yanıt değerlendirmelerini içeri aktar</summary><label htmlFor="inbox-review-json">Yanıt değerlendirme JSON’u</label><textarea id="inbox-review-json" value={text} onChange={e=>setText(e.target.value)} rows={8} maxLength={150000} placeholder={'{"reviews":[{"eventId":"kayıt","version":0,"bodyHash":"dışa aktarılan hash","classification":"question","excerpt":"Yanıttan aynen alıntı","summary":"Yanıtın özeti","nextAction":"Önerilen sonraki işlem","draft":"Cevap taslağı"}]}'} /><button disabled={busy||!text.trim()} onClick={importBatch}>Değerlendirmeleri kaydet</button></details>{notice&&<p role="status">{notice}</p>}</section>;
}
function ReplyDraft({message,onSaved}){
 const [draft,setDraft]=useState(message.replyDraft||''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{setDraft(message.replyDraft||'')},[message.replyDraft,message.draftVersion]);
 async function save(){setBusy(true);setNotice('');try{const r=await fetch('/api/inbox',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({eventId:message.eventId,draft,version:message.draftVersion})}),d=await r.json();if(!r.ok)throw new Error(d.error);setNotice('Taslak kaydedildi. E-posta gönderilmedi.');await onSaved()}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 return <details><summary>Cevap taslağını incele ve düzenle</summary>{message.replySummary&&<p>{message.replySummary}</p>}<label style={{display:'block'}}>Bu e-postaya ait cevap<textarea value={draft} onChange={e=>setDraft(e.target.value)} maxLength={10000} rows={7} style={{width:'100%',boxSizing:'border-box'}} /></label><button disabled={busy||!draft.trim()} onClick={save}>{busy?'Kaydediliyor…':'Taslağı kaydet'}</button><small> Bu işlem yalnızca taslağı kaydeder.</small>{notice&&<p role="status">{notice}</p>}</details>;
}
export default function InboxManager(){
 const [messages,setMessages]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/inbox',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setMessages(d.messages||[])}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[]);
 async function process(eventId){setBusy(true);setError('');try{const r=await fetch('/api/inbox',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({eventId:typeof eventId==='string'?eventId:undefined})}),d=await r.json();if(!r.ok)throw new Error(d.error);if(d.skipped)setError(d.skipped==='inbox-not-configured'?'Gelen e-posta bağlantısını Ayarlar üzerinden tamamlayın.':'Başka işlem sürüyor.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel"><div className="section-title"><div><h2>Gelen Yanıtlar</h2><small>Doğrulanmış göndericiler CRM kaydıyla eşleştirilir; ücretli AI çağrısı yapılmadan inceleme kuyruğuna alınır.</small></div><button onClick={process} disabled={busy}>{busy?'İşleniyor…':'Gelenleri işle'}</button></div><InboxReviewTransfer onSaved={load}/>{error&&<p role="status">{error}</p>}{!messages.length?<p>Henüz alınan yanıt yok. Bağlantı durumu Ayarlar sayfasında.</p>:messages.map(x=><article key={x.eventId}><b>{x.sender||'Gönderici kontrol ediliyor'} · {x.subject}</b><p>{labels[x.status]||x.status}</p><details><summary>Yanıt metni</summary><p style={{whiteSpace:'pre-wrap'}}>{x.body}</p></details>{x.reviewAssessment?.method&&<p>İnceleyici değerlendirmesi · {x.reviewAssessment.classification}<br/>Sonraki işlem: {x.reviewAssessment.nextAction}</p>}{x.status==='analyzed'&&x.draftVersion>0&&<ReplyDraft message={x} onSaved={load}/>} {x.status==='analyzed'&&!x.draftVersion&&<p>Bu eski kayıt için e-postaya özel taslak bulunmuyor.</p>}{x.status==='review-required'&&<div><small>Kontrol gerekçesi: {x.reviewReason||"Gönderici veya eşleşme doğrulanamadı."}</small><p><button disabled={busy} onClick={()=>process(x.eventId)}>Göndericiyi ve CRM eşleşmesini tekrar kontrol et</button></p></div>}</article>)}</section>;
}
