"use client";
import {useEffect,useState} from 'react';
const labels={queued:'İşlem bekliyor',analyzed:'Analiz edildi','review-required':'İnsan incelemesi gerekiyor'};
function ReplyDraft({message,onSaved}){
 const [draft,setDraft]=useState(message.replyDraft||''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{setDraft(message.replyDraft||'')},[message.replyDraft,message.draftVersion]);
 async function save(){setBusy(true);setNotice('');try{const r=await fetch('/api/inbox',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({eventId:message.eventId,draft,version:message.draftVersion})}),d=await r.json();if(!r.ok)throw new Error(d.error);setNotice('Taslak kaydedildi. E-posta gönderilmedi.');await onSaved()}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 return <details><summary>Cevap taslağını incele ve düzenle</summary>{message.replySummary&&<p>{message.replySummary}</p>}<label style={{display:'block'}}>Bu e-postaya ait cevap<textarea value={draft} onChange={e=>setDraft(e.target.value)} maxLength={10000} rows={7} style={{width:'100%',boxSizing:'border-box'}} /></label><button disabled={busy||!draft.trim()} onClick={save}>{busy?'Kaydediliyor…':'Taslağı kaydet'}</button><small> Bu işlem yalnızca taslağı kaydeder.</small>{notice&&<p role="status">{notice}</p>}</details>;
}
export default function InboxManager(){
 const [messages,setMessages]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/inbox',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setMessages(d.messages||[])}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[]);
 async function process(eventId){setBusy(true);setError('');try{const r=await fetch('/api/inbox',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({eventId:typeof eventId==='string'?eventId:undefined})}),d=await r.json();if(!r.ok)throw new Error(d.error);if(d.skipped)setError(d.skipped==='inbox-not-configured'?'Gelen e-posta bağlantısını Ayarlar üzerinden tamamlayın.':'Başka işlem sürüyor.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel"><div className="section-title"><div><h2>Gelen Yanıtlar</h2><small>Doğrulanmış göndericiler CRM kaydıyla eşleştirilir; yanıt taslakları inceleme bekler.</small></div><button onClick={process} disabled={busy}>{busy?'İşleniyor…':'Gelenleri işle'}</button></div>{error&&<p role="status">{error}</p>}{!messages.length?<p>Henüz alınan yanıt yok. Bağlantı durumu Ayarlar sayfasında.</p>:messages.map(x=><article key={x.eventId}><b>{x.sender||'Gönderici kontrol ediliyor'} · {x.subject}</b><p>{labels[x.status]||x.status}</p><details><summary>Yanıt metni</summary><p style={{whiteSpace:'pre-wrap'}}>{x.body}</p></details>{x.status==='analyzed'&&x.draftVersion>0&&<ReplyDraft message={x} onSaved={load}/>} {x.status==='analyzed'&&!x.draftVersion&&<p>Bu eski kayıt için e-postaya özel taslak bulunmuyor.</p>}{x.status==='review-required'&&<div><small>Kontrol gerekçesi: {x.reviewReason||"Gönderici veya eşleşme doğrulanamadı."}</small><p><button disabled={busy} onClick={()=>process(x.eventId)}>Göndericiyi ve CRM eşleşmesini tekrar kontrol et</button></p></div>}</article>)}</section>;
}
