"use client";
import {useEffect,useState} from "react";
export default function LeadFinder(){
 const [country,setCountry]=useState("Türkiye"),[city,setCity]=useState("Sivas"),[sector,setSector]=useState("Tekstil ve giyim"),[items,setItems]=useState([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 async function load(){const r=await fetch("/api/lead-finder",{cache:"no-store"}),d=await r.json();if(r.ok)setItems(d.leads||[])}
 useEffect(()=>{load()},[]);
 async function run(e){e.preventDefault();setBusy(true);setMsg("");try{const r=await fetch("/api/lead-finder",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({country,city,sector,limit:12})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Tarama başlatılamadı.");setMsg(`${d.saved} yeni işletme bulundu · ${d.duplicates} tekrar elendi`);await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <section style={{display:"grid",gap:14}}><article className="panel"><h2>Lead Finder</h2><p>Ülke → şehir → sektör seç. Araştırma ajanı gerçek işletmeleri bulur ve tekrarları otomatik eler.</p><form onSubmit={run} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}><label>Ülke<input value={country} onChange={e=>setCountry(e.target.value)} required/></label><label>Şehir<input value={city} onChange={e=>setCity(e.target.value)} required/></label><label>Sektör<select value={sector} onChange={e=>setSector(e.target.value)}><option>Tekstil ve giyim</option><option>Sağlık</option><option>Turizm ve otel</option><option>Restoran ve kafe</option><option>Gayrimenkul</option><option>Otomotiv</option><option>Güzellik ve bakım</option><option>E-ticaret</option><option>Hukuk</option><option>Eğitim</option><option>İnşaat</option><option>Yazılım ve teknoloji</option></select></label><button disabled={busy}>{busy?"Ajanlar araştırıyor…":"Müşteri bul"}</button></form>{msg&&<p className="client-message">{msg}</p>}</article><article className="panel"><h2>Bulunan İşletmeler</h2>{!items.length?<div className="empty">Henüz Lead Finder kaydı yok.</div>:<div className="client-list">{items.map(x=><article className="client-row" key={x.id}><div className="client-avatar">{x.businessName?.slice(0,1)}</div><div><b>{x.businessName}</b><small>{[x.country,x.city,x.sector].filter(Boolean).join(" · ")}</small><small>{x.website||"Web sitesi doğrulanmadı"}{x.phone?" · "+x.phone:""}{x.email?" · "+x.email:""}</small>{x.sourceUrl&&<small><a href={x.sourceUrl} target="_blank" rel="noreferrer">Kaynağı doğrula ↗</a></small>}</div><span>Bulundu</span></article>)}</div>}</article></section>

}
