"use client";
import {useEffect,useState} from "react";
export default function LeadFinder(){
 const [country,setCountry]=useState("Türkiye"),[city,setCity]=useState("Sivas"),[sector,setSector]=useState("Tekstil ve giyim"),[items,setItems]=useState([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const [prospects,setProspects]=useState([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(""),[query,setQuery]=useState(""),[page,setPage]=useState(1),[review,setReview]=useState(null);
 async function load(){
  setLoading(true);setLoadError("");
  const results=await Promise.allSettled([fetch("/api/prospects",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Otomatik adaylar alınamadı.");setProspects(d.prospects||[]);setReview(d.review||null)}),fetch("/api/lead-finder",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Elle arama kayıtları alınamadı.");setItems(d.leads||[])})]);
  setLoadError(results.filter(x=>x.status==="rejected").map(x=>x.reason?.message||"Kayıtlar alınamadı.").join(" · "));setLoading(false);
 }
 const filtered=[...prospects].sort((a,b)=>(b.selectionPriority??-1)-(a.selectionPriority??-1)).filter(x=>[x.name,x.country,x.city,x.sector].join(" ").toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR")));
 const pages=Math.max(1,Math.ceil(filtered.length/25)),currentPage=Math.min(page,pages),visible=filtered.slice((currentPage-1)*25,currentPage*25);
 const stateLabel=x=>({completed:"Analiz tamamlandı",running:"Analiz sürüyor",queued:"Analiz kuyruğunda",failed:"Analiz yeniden kontrol edilmeli"}[x.scanStatus]||({new:"Analiz bekliyor","analysis-queued":"Analiz kuyruğunda",analyzed:"Analiz tamamlandı"}[x.status])||"Durum kontrolü bekliyor");
 useEffect(()=>{load()},[]);
 async function qualify(){setBusy(true);setMsg("");try{const r=await fetch("/api/lead-finder",{method:"PATCH"}),d=await r.json();if(!r.ok)throw new Error(d.error||"Puanlama yapılamadı.");setItems(d.leads||[]);setMsg(`${d.count} işletme Qualification ajanı tarafından puanlandı.`)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function run(e){e.preventDefault();setBusy(true);setMsg("");try{const r=await fetch("/api/lead-finder",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({country,city,sector,limit:12})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Tarama başlatılamadı.");setMsg(`${d.saved} yeni işletme bulundu · ${d.duplicates} tekrar elendi`);await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <section style={{display:"grid",gap:14}}><article className="panel">
 <div className="section-title"><div><h2>Otomatik Ajanların Bulduğu İşletmeler</h2><small>{loading?"Kayıtlar yükleniyor…":`${prospects.length} aday · ${filtered.length} eşleşme`} · Öncelikli adaylar önce gösterilir</small></div><button type="button" onClick={load} disabled={loading}>{loading?"Yükleniyor…":"Yenile"}</button></div>
 <p>Global tarama havuzu. Bu işletmeler henüz ödeme yapan müşteriler değildir; uygunluk puanı satış veya görünürlük garantisi değildir.</p>
 {review&&<p>{review.awaitingAnalysis} adayın analizi bekliyor · {review.qualified} aday iletişim seçimine uygun. Uygunluk puanı ile analiz sonucu ayrı değerlendirilir.</p>}
 {loadError&&<p role="alert" className="client-message">{loadError}</p>}
 <label style={{display:"grid",gap:8}}>İşletme, ülke, şehir veya sektör ara<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Örn. Almanya, makine, Bursa"/></label>
 {loading?<p role="status">Aday listesi yükleniyor…</p>:!filtered.length?<div className="empty">{loadError?"Liste yüklenemedi. Yenile düğmesiyle tekrar deneyin.":query?"Bu aramaya uygun aday yok.":"Otomatik tarama havuzunda henüz aday yok."}</div>:<div className="client-list">{visible.map(x=><article className="panel" key={x.id} style={{display:"grid",gap:10,marginTop:12,overflowWrap:"anywhere"}}><div><b>{x.name}</b><small style={{display:"block"}}>{[x.country,x.city,x.sector].filter(Boolean).join(" · ")}</small><small>{x.domain||"Web sitesi kaydı yok"}</small></div><span>Uygunluk: {x.qualificationLevel==="hot"?"Sıcak":x.qualificationLevel==="warm"?"Orta":x.qualificationLevel==="low"?"Düşük":"Puan bekliyor"}{x.qualificationScore!=null?` · ${x.qualificationScore}/100`:""}</span><small>{stateLabel(x)}</small><details><summary>Seçim gerekçesi ve analiz kanıtları</summary><div style={{display:"grid",gap:10,marginTop:12}}>
 {x.selectionPriority!==null&&x.selectionPriority!==undefined&&<small>Karşılaştırmalı öncelik: {x.selectionPriority} · Satış olasılığı değildir.</small>}
 {x.selectionReasons?.length>0&&<ul>{x.selectionReasons.map((reason,i)=><li key={i}>{reason}</li>)}</ul>}
 {x.qualificationReason&&<p>Uygunluk gerekçesi: {x.qualificationReason}</p>}
 {x.evidence?.sourceUrl?<p><a href={x.evidence.sourceUrl} target="_blank" rel="noopener noreferrer">{x.evidence.officialSource?"İşletmenin resmî kaynağını aç":"Keşif kaynağını aç"} ↗</a>{x.evidence.specialty&&<small style={{display:"block"}}>{x.evidence.specialty}</small>}</p>:<p>Kaynak bağlantısı kaydedilmemiş.</p>}
 {x.evidence?.analyzed?<><b>AI görünürlük: {x.evidence.score}/100 · {x.evidence.provider}</b>{x.evidence.analyzedAt&&<small>Analiz: {new Date(x.evidence.analyzedAt).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul"})}</small>}<div><b>Analizde bulunan ihtiyaçlar</b><ul>{x.evidence.findings.slice(0,3).map((v,i)=><li key={i}>{v}</li>)}</ul></div><div><b>Önerilen çözümler</b><ul>{x.evidence.recommendations.slice(0,3).map((v,i)=><li key={i}>{v}</li>)}</ul></div><small>Bulgular sağlayıcı analizidir; çözümün uygulandığı veya sonuç verdiği anlamına gelmez.</small></>:<p>Kanıt ölçütlerini karşılayan tamamlanmış analiz yok. Somut ihtiyaç ve çözüm henüz doğrulanmadı.</p>}
 {x.evidence?.contactSourceUrl&&<a href={x.evidence.contactSourceUrl} target="_blank" rel="noopener noreferrer">Kurumsal iletişim kaynağını aç ↗</a>}
 </div></details></article>)}</div>}

 {filtered.length>25&&<div style={{display:"flex",gap:12,alignItems:"center",flexWrap:"wrap",marginTop:16}}><button type="button" disabled={currentPage<=1||loading} onClick={()=>setPage(currentPage-1)}>Önceki</button><span>Sayfa {currentPage} / {pages}</span><button type="button" disabled={currentPage>=pages||loading} onClick={()=>setPage(currentPage+1)}>Sonraki</button></div>}
 </article><article className="panel"><h2>Lead Finder</h2><p>Ülke → şehir → sektör seç. Araştırma ajanı gerçek işletmeleri bulur ve tekrarları otomatik eler.</p><form onSubmit={run} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}><label>Ülke<input value={country} onChange={e=>setCountry(e.target.value)} required/></label><label>Şehir<input value={city} onChange={e=>setCity(e.target.value)} required/></label><label>Sektör<select value={sector} onChange={e=>setSector(e.target.value)}><option>Tekstil ve giyim</option><option>Sağlık</option><option>Turizm ve otel</option><option>Restoran ve kafe</option><option>Gayrimenkul</option><option>Otomotiv</option><option>Güzellik ve bakım</option><option>E-ticaret</option><option>Hukuk</option><option>Eğitim</option><option>İnşaat</option><option>Yazılım ve teknoloji</option></select></label><button disabled={busy}>{busy?"Ajanlar araştırıyor…":"Müşteri bul"}</button></form>{msg&&<p className="client-message">{msg}</p>}</article><article className="panel"><div className="section-title"><div><h2>Elle Aramada Bulunan İşletmeler</h2><small>Qualification: Sıcak 75–100 · Orta 50–74 · Düşük 0–49</small></div><button onClick={qualify} disabled={busy}>{busy?"Puanlanıyor…":"Qualification çalıştır"}</button></div>{!items.length?<div className="empty">Henüz elle arama kaydı yok. Otomatik ajan adayları üstteki listede gösterilir.</div>:<div className="client-list">{items.map(x=><article className="client-row" key={x.id}><div className="client-avatar">{x.businessName?.slice(0,1)}</div><div><b>{x.businessName}</b><small>{[x.country,x.city,x.sector].filter(Boolean).join(" · ")}</small><small>{x.website||"Web sitesi doğrulanmadı"}{x.phone?" · "+x.phone:""}{x.email?" · "+x.email:""}</small>{x.sourceUrl&&<small><a href={x.sourceUrl} target="_blank" rel="noreferrer">Kaynağı doğrula ↗</a></small>}{x.qualificationReason&&<small>Qualification: {x.qualificationReason}</small>}</div><span>{x.qualificationLevel==="hot"?"🔥 Sıcak":x.qualificationLevel==="warm"?"● Orta":x.qualificationLevel==="low"?"○ Düşük":"Bulundu"}{x.qualificationScore?` · ${x.qualificationScore}/100`:""}</span></article>)}</div>}</article></section>

}
