"use client";
import {Fragment,useState} from "react";
export default function OutreachDailyReportSummary({data}){
 const [opened,setOpened]=useState(null);
 return <section className="er-outreach" aria-labelledby="er-outreach-title"><div className="er-section-title"><span>07</span><h2 id="er-outreach-title">Bugünkü firma e-postaları</h2></div>
 {!data?.available?<p className="er-error" role="alert">E-posta kayıtları alınamadı. Gönderim sayısı bilinmiyor; raporu yenileyin.</p>:<>
 <p><b>{data.accepted}</b> sağlayıcı tarafından kabul edilen e-posta · <b>{data.uncertain}</b> sonucu belirsiz işlem.</p>
 <p className="er-muted">Türkiye saatiyle rapor gününe ait kalıcı gönderim kayıtları. Taslaklar bu tabloya dahil edilmez. Sağlayıcının kabulü, alıcının kutusuna teslim edildiği anlamına gelmez. Kayıt zamanı gönderim işleminin kaydedildiği zamandır.</p>
 {data.rows.length?<div className="er-mail-scroll" role="region" aria-label="Firma e-posta tablosu" tabIndex={0}><table className="er-mail-table"><caption>Firma, konum, alıcı ve gönderilen mesaj</caption><thead><tr>{['Firma','Ülke / şehir','Alıcı e-posta','Kayıt zamanı / durum','E-posta içeriği'].map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{data.rows.map(row=><Fragment key={row.id}><tr><th scope="row">{row.name}<small>Firma iletişimi · {row.kind}</small></th><td>{row.country||'Ülke kaydı yok'}<small>{row.city||'Şehir kaydı yok'}</small></td><td>{row.recipient||'Alıcı kaydı yok'}</td><td><time dateTime={row.recordedAt}>{new Date(row.recordedAt).toLocaleTimeString('tr-TR',{timeZone:'Europe/Istanbul',hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time><small>{row.status}</small></td><td><button type="button" className="er-mail-open" aria-expanded={opened===row.id} aria-label={`${row.name}: e-posta içeriğini ${opened===row.id?'kapat':'aç'}`} onClick={()=>setOpened(opened===row.id?null:row.id)}>{opened===row.id?'İçeriği kapat':'İçeriği gör'}</button></td></tr>{opened===row.id&&<tr className="er-mail-expanded"><td colSpan={5}><div className="er-mail-content"><p><b>Konu:</b> {row.subject||'Konu kaydı yok'}</p><p><b>Gönderen:</b> {row.sender||'Gönderen kaydı yok'}</p><p><b>Alıcı:</b> {row.recipient}</p>{!row.accepted&&<p>Bu mesajın gönderildiği doğrulanmadı; kayıtlı gönderim denemesinin içeriğidir.</p>}<p className="er-mail-body">{row.body||'Mesaj içeriği kaydı yok.'}</p><small>Kalıcı gönderim kaydının metin görünümü.</small></div></td></tr>}</Fragment>)}</tbody></table></div>:<p>Bu rapor gününde kayıtlı firma e-postası yok.</p>}
 {data.limited&&<p className="er-muted">İlk 500 kayıt gösteriliyor; sayımlar tüm kayıtları kapsar.</p>}
 </>}
 <style>{`.er-outreach{min-width:0}.er-mail-scroll{max-width:100%;overflow-x:auto;border:1px solid #dce5eb;border-radius:10px}.er-mail-table{width:100%;border-collapse:collapse;table-layout:fixed;color:#172c40;font-size:12px}.er-mail-table caption{text-align:left;padding:12px;font-weight:bold}.er-mail-table th,.er-mail-table td{padding:12px 9px;text-align:left;vertical-align:top;border-top:1px solid #dce5eb;overflow-wrap:anywhere}.er-mail-table thead{background:#edf7f4}.er-mail-table small{display:block;font-size:11px;font-weight:normal;line-height:1.5;margin-top:6px;color:#526d80}.er-mail-table .er-mail-open{cursor:pointer;min-height:44px;line-height:1.5;padding:8px 0;color:#13786f;font-weight:bold}.er-mail-table .er-mail-open:focus-visible{outline:3px solid #18a999;outline-offset:2px}.er-mail-content{margin-top:8px}.er-mail-content p{font-size:12px}.er-mail-body{white-space:pre-wrap}.er-mail-expanded{background:#f8fafb}.er-mail-expanded .er-mail-content{max-width:760px;padding:8px 12px}@media(max-width:640px){.er-mail-table{min-width:680px}.er-mail-scroll:focus-visible{outline:3px solid #18a999}}@media print{.er-mail-scroll{overflow:visible;border-radius:0}.er-mail-table{min-width:0;table-layout:fixed;font-size:9px}.er-mail-table th,.er-mail-table td{padding:7px 4px}.er-mail-table thead{display:table-header-group}.er-mail-table tr{break-inside:avoid}.er-mail-content p,.er-mail-table small{font-size:9px}}`}</style>
 </section>
}
