"use client";
import {useEffect,useMemo,useState} from "react";
import {useLanguage} from "./LanguageProvider";

const copy={
  tr:{loading:"Ödeme bilgileri hazırlanıyor…",loadError:"Ödeme bilgisi alınamadı.",package:"Paket seçimi",recommended:"için önerilen paket",setup:"Kurulum",monthly:"Aylık",first:"Önerilen ilk ödeme",tracking:"ChatGPT + Gemini + Perplexity görünürlük takibi",plan:"GEO/AEO iyileştirme planı",report:"Aylık görünürlük raporu",country:"Fiyat bölgesi",transfer:"Havale / EFT",card:"Kartla ödeme",international:"Bu müşteri için fiyat seçilen ülkeye göre hazırlandı. Bu para biriminde canlı ödeme kanalı henüz etkin değil; ödeme sağlayıcısı aktif edildiğinde aynı fiyat otomatik kullanılacak.",paid:"✓ Ödemeniz onaylandı",paidHelp:"Önce e-posta adresinizi doğrulayın, ardından şifrenizi oluşturun.",email:"E-posta",password:"Şifre",sendCode:"Doğrulama kodu gönder",resend:"Kodu tekrar gönder",sending:"Gönderiliyor…",code:"6 haneli kod",verify:"Kodu doğrula",verified:"✓ E-posta doğrulandı",verifying:"Doğrulanıyor…",create:"Müşteri hesabımı oluştur",creating:"Hesap oluşturuluyor…",passwordHelp:"Şifre en az 10 karakter olmalıdır.",consent:"Mesafeli Hizmet Sözleşmesi ile İptal / İade Politikasını okudum. Hizmetin 14 günlük cayma süresi dolmadan başlamasını açıkça onaylıyorum ve hizmetin ifasına başlanmasının cayma hakkımı etkileyebileceği konusunda bilgilendirildim.",agreement:"Hizmet Sözleşmesi",refund:"İptal / İade Politikası",bank:"Banka",holder:"Hesap sahibi",iban:"IBAN",copy:"⧉ IBAN'ı kopyala",copied:"✓ IBAN kopyalandı",ibanHelp:"Güvenlik için IBAN ekranda maskelidir. Kopyaladığınızda gerçek IBAN panoya alınır.",reference:"Açıklama kodu",referenceHelp:"Ödeme açıklamasına bu kodu yazın. Banka kontrolü yapılmadan paket aktif edilmez.",reportPaid:"Ödemeyi yaptım",reporting:"Bildiriliyor…",reported:"✓ Ödeme bildirildi",approved:"✓ Ödeme onaylandı",transferUnavailable:"Bu para birimi için banka ödeme kanalı henüz etkin değil.",cardUnavailable:"iyzico kartla ödeme yakında. Şimdilik kullanılabilir ödeme kanallarını kullanabilirsiniz.",name:"Ad soyad",phone:"Telefon",address:"Adres",secure:"Kartla güvenli ödemeye geç",opening:"Güvenli ödeme açılıyor…",consentFirst:"Önce sözleşme onayını verin",cardHelp:"Kart bilgileriniz AI Visibility sunucusuna gönderilmez; güvenli ödeme sağlayıcısında girilir.",close:"Ödeme formunu kapat",sent:"6 haneli kod e-posta adresinize gönderildi.",ibanError:"IBAN kopyalanamadı.",requestError:"Bildirim alınamadı.",setupError:"Müşteri hesabı oluşturulamadı.",codeError:"Kod gönderilemedi.",verifyError:"Kod doğrulanamadı."},
  en:{loading:"Preparing payment details…",loadError:"Unable to load payment details.",package:"Package",recommended:"recommended package",setup:"Setup",monthly:"Monthly",first:"Recommended first payment",tracking:"ChatGPT + Gemini + Perplexity visibility monitoring",plan:"GEO/AEO improvement plan",report:"Monthly visibility report",country:"Pricing region",transfer:"Bank transfer",card:"Card payment",international:"Pricing has been prepared in the currency of the selected country. Live payment for this currency is not enabled yet; the same price will be used automatically when the payment provider is activated.",paid:"✓ Payment approved",paidHelp:"Verify your email first, then create your password.",email:"Email",password:"Password",sendCode:"Send verification code",resend:"Send code again",sending:"Sending…",code:"6-digit code",verify:"Verify code",verified:"✓ Email verified",verifying:"Verifying…",create:"Create my customer account",creating:"Creating account…",passwordHelp:"Password must be at least 10 characters.",consent:"I have read the Distance Service Agreement and Cancellation / Refund Policy. I explicitly consent to the service starting before the 14-day withdrawal period ends and understand that performance of the service may affect my withdrawal right.",agreement:"Service Agreement",refund:"Cancellation / Refund Policy",bank:"Bank",holder:"Account holder",iban:"IBAN",copy:"⧉ Copy IBAN",copied:"✓ IBAN copied",ibanHelp:"The IBAN is masked on screen for security. Copying places the full IBAN on your clipboard.",reference:"Payment reference",referenceHelp:"Include this code in the payment description. The package is not activated until payment is verified.",reportPaid:"I have paid",reporting:"Reporting…",reported:"✓ Payment reported",approved:"✓ Payment approved",transferUnavailable:"Bank transfer is not enabled for this currency yet.",cardUnavailable:"iyzico card payment is coming soon. Please use the currently available payment methods.",name:"Full name",phone:"Phone",address:"Address",secure:"Continue to secure card payment",opening:"Opening secure payment…",consentFirst:"Accept the agreement first",cardHelp:"Your card details are not sent to AI Visibility servers; they are entered with the secure payment provider.",close:"Close payment form",sent:"A 6-digit code was sent to your email.",ibanError:"Could not copy IBAN.",requestError:"Could not submit payment report.",setupError:"Could not create customer account.",codeError:"Could not send code.",verifyError:"Could not verify code."}
};

function money(amount,currency,lang){
  const locale=currency==="TRY"?"tr-TR":currency==="GBP"?"en-GB":currency==="EUR"?"en-IE":"en-US";
  try{return new Intl.NumberFormat(locale,{style:"currency",currency,maximumFractionDigits:0}).format(Number(amount)||0)}catch{return `${Number(amount)||0} ${currency}`}
}

export default function PaymentManager({token}){
  const {lang}=useLanguage();const c=copy[lang]||copy.tr;
  const [d,setD]=useState(null),[err,setErr]=useState(""),[copied,setCopied]=useState(false),[reporting,setReporting]=useState(false),[reported,setReported]=useState(false),[cardBusy,setCardBusy]=useState(false),[iframeUrl,setIframeUrl]=useState(""),[consent,setConsent]=useState(false),[cardForm,setCardForm]=useState({name:"",email:"",phone:"",address:""}),[setupBusy,setSetupBusy]=useState(false),[setupForm,setSetupForm]=useState({email:"",password:""}),[code,setCode]=useState(""),[codeSent,setCodeSent]=useState(false),[emailVerified,setEmailVerified]=useState(false),[verifyBusy,setVerifyBusy]=useState(false),[verifyMsg,setVerifyMsg]=useState("");
  useEffect(()=>{fetch("/api/payment?token="+encodeURIComponent(token),{cache:"no-store",headers:{"accept-language":lang}}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||c.loadError);return j}).then(setD).catch(e=>setErr(e.message))},[token,lang]);
  const currency=d?.plan?.currency||"TRY";
  const firstPayment=useMemo(()=>d?money(d.plan?.firstPayment||0,currency,lang):"",[d,currency,lang]);
  if(err)return <section className="panel"><p className="client-message">{err}</p></section>;
  if(!d)return <section className="panel"><p>{c.loading}</p></section>;
  const ref=d.payment?.referenceCode||("AIV-"+d.client.id.slice(0,8)).toUpperCase();
  const rawIban=String(d.bank?.iban||"").replace(/\s+/g,"");
  const maskedIban=rawIban?("TR** **** **** **** **** **"+rawIban.slice(-4)):"";
  async function copyIban(){try{await navigator.clipboard.writeText(rawIban);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setErr(c.ibanError)}}
  async function reportPaid(){if(!d.payment?.id)return;setReporting(true);setErr("");try{const r=await fetch("/api/payment",{method:"POST",headers:{"content-type":"application/json","accept-language":lang},body:JSON.stringify({paymentId:d.payment.id,token,consent})});const j=await r.json();if(!r.ok)throw new Error(j.error||c.requestError);setReported(true);setD({...d,payment:j.payment})}catch(e){setErr(e.message)}finally{setReporting(false)}}
  async function sendCode(){setVerifyBusy(true);setVerifyMsg("");try{const r=await fetch("/api/client-auth/send-code",{method:"POST",headers:{"content-type":"application/json","accept-language":lang},body:JSON.stringify({token,email:setupForm.email,language:lang})});const j=await r.json();if(!r.ok)throw new Error(j.error||c.codeError);setCodeSent(true);setEmailVerified(false);setVerifyMsg(c.sent)}catch(e){setVerifyMsg(e.message)}finally{setVerifyBusy(false)}}
  async function verifyCode(){setVerifyBusy(true);setVerifyMsg("");try{const r=await fetch("/api/client-auth/verify-code",{method:"POST",headers:{"content-type":"application/json","accept-language":lang},body:JSON.stringify({token,email:setupForm.email,code,language:lang})});const j=await r.json();if(!r.ok)throw new Error(j.error||c.verifyError);setEmailVerified(true);setVerifyMsg(c.verified)}catch(e){setEmailVerified(false);setVerifyMsg(e.message)}finally{setVerifyBusy(false)}}
  async function setupCustomer(e){e.preventDefault();setSetupBusy(true);setErr("");try{const r=await fetch("/api/client-auth/setup",{method:"POST",headers:{"content-type":"application/json","accept-language":lang},body:JSON.stringify({token,email:setupForm.email,password:setupForm.password,language:lang})});const j=await r.json();if(!r.ok)throw new Error(j.error||c.setupError);window.location.href="/musteri-panel"}catch(e){setErr(e.message)}finally{setSetupBusy(false)}}
  async function startCardPayment(e){e.preventDefault();setCardBusy(true);setErr("");try{const r=await fetch("/api/paytr/token",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({paymentId:d.payment?.id,token,consent,...cardForm})});const j=await r.json();if(!r.ok)throw new Error([j.error,j.detail].filter(Boolean).join(" · "));setIframeUrl(j.iframeUrl)}catch(e){setErr(e.message)}finally{setCardBusy(false)}}

  return <>
    {d.payment?.status==="paid"&&<section className="panel" style={{marginBottom:16}}><h2>{c.paid}</h2><p>{c.paidHelp}</p><form className="scan-form" onSubmit={setupCustomer} style={{marginTop:12}}><label>{c.email}<input type="email" value={setupForm.email} onChange={e=>{setSetupForm({...setupForm,email:e.target.value});setEmailVerified(false);setCodeSent(false);setCode("")}} required/></label><button type="button" onClick={sendCode} disabled={verifyBusy||!setupForm.email}>{verifyBusy?c.sending:codeSent?c.resend:c.sendCode}</button>{codeSent&&<><label>{c.code}<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} required/></label><button type="button" onClick={verifyCode} disabled={verifyBusy||code.length!==6||emailVerified}>{emailVerified?c.verified:verifyBusy?c.verifying:c.verify}</button></>}{verifyMsg&&<small>{verifyMsg}</small>}<label>{c.password}<input type="password" value={setupForm.password} onChange={e=>setSetupForm({...setupForm,password:e.target.value})} minLength={10} required disabled={!emailVerified}/></label><small>{c.passwordHelp}</small><button disabled={setupBusy||!emailVerified}>{setupBusy?c.creating:c.create}</button></form></section>}
    <section className="grid reports-grid">
      <article className="panel"><h2>{c.package}</h2><p><b>{d.client.name}</b> {c.recommended}</p><div className="content-plan"><h3>{d.plan.name}</h3><p><b>{c.country}:</b> {d.profile?.country||"—"} · <strong>{currency}</strong></p><ul><li>{c.setup}: {d.plan.setup}</li><li>{c.monthly}: {d.plan.monthly}</li><li><strong>{c.first}: {firstPayment}</strong></li><li>{c.tracking}</li><li>{c.plan}</li><li>{c.report}</li></ul></div>{d.internationalPaymentPending&&<div className="empty" style={{marginTop:12}}>{c.international}</div>}</article>
      <article className="panel"><div className="content-plan" style={{marginBottom:18}}><label style={{display:"flex",gap:10,alignItems:"flex-start"}}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} style={{width:18,height:18,marginTop:2}}/><span>{c.consent}</span></label><small><a href="/mesafeli-hizmet-sozlesmesi" target="_blank">{c.agreement}</a> · <a href="/iptal-iade" target="_blank">{c.refund}</a></small></div>
      <h2>{c.transfer}</h2>{d.transferReady?<div className="content-plan"><b>{c.bank}</b><p>{d.bank.bankName}</p><b>{c.holder}</b><p>{d.bank.accountHolder}</p><b>{c.iban}</b><p style={{wordBreak:"break-all"}}>{maskedIban}</p><button type="button" onClick={copyIban}>{copied?c.copied:c.copy}</button><small>{c.ibanHelp}</small><b>{c.reference}</b><p>{ref}</p><small>{c.referenceHelp}</small><button type="button" onClick={reportPaid} disabled={!consent||reporting||reported||d.payment?.status==="customer-reported"||d.payment?.status==="paid"} style={{marginTop:14}}>{d.payment?.status==="paid"?c.approved:reported||d.payment?.status==="customer-reported"?c.reported:reporting?c.reporting:c.reportPaid}</button></div>:<div className="empty">{c.transferUnavailable}</div>}
      <h2 style={{marginTop:20}}>{c.card}</h2>{d.cardReady?<div className="content-plan">{!iframeUrl?<form onSubmit={startCardPayment} className="scan-form" style={{margin:0}}><label>{c.name}<input value={cardForm.name} onChange={e=>setCardForm({...cardForm,name:e.target.value})} required/></label><label>{c.email}<input type="email" value={cardForm.email} onChange={e=>setCardForm({...cardForm,email:e.target.value})} required/></label><label>{c.phone}<input value={cardForm.phone} onChange={e=>setCardForm({...cardForm,phone:e.target.value})} required/></label><label>{c.address}<textarea value={cardForm.address} onChange={e=>setCardForm({...cardForm,address:e.target.value})} required/></label><button disabled={cardBusy||!consent}>{cardBusy?c.opening:!consent?c.consentFirst:c.secure}</button><small>{c.cardHelp}</small></form>:<div><iframe title="Secure Payment" src={iframeUrl} style={{width:"100%",minHeight:720,border:0,borderRadius:12,background:"#fff"}}/><button type="button" onClick={()=>setIframeUrl("")} style={{marginTop:10}}>{c.close}</button></div>}</div>:<div className="empty">{c.cardUnavailable}</div>}</article>
    </section>
  </>;
}
