"use client";
import {useEffect,useState} from 'react';
export default function PilotAccessManager(){
 const [clients,setClients]=useState([]),[clientId,setClientId]=useState(''),[email,setEmail]=useState(''),[days,setDays]=useState(7),[reason,setReason]=useState('Ücretsiz gerçek işletme analiz pilotu.'),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[url,setUrl]=useState('');
 async function load(){try{const r=await fetch('/api/admin-pilots',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setClients(d.clients||[])}catch(e){setMsg(e.message)}}
 useEffect(()=>{load()},[]);
 async function submit(action){setBusy(true);setMsg('');setUrl('');try{const r=await fetch('/api/admin-pilots',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({clientId,email,days:Number(days),reason,action})}),d=await r.json();if(!r.ok)throw Error(d.error);setUrl(d.pilotUrl||'');setMsg(action==='revoke'?'Pilot erişimi kaldırıldı.':'Pilot açıldı. Ödeme veya gelir kaydı oluşturulmadı.');await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 const selected=clients.find(x=>x.id===clientId);
 return <section className="content-plan" style={{marginBottom:16}}><h3>Ücretsiz işletme pilotu</h3><p>Analiz, bulgular ve rapor erişimi; en fazla 30 gün. Uygulama hizmeti ve banka onayı bu kapsama dahil değildir.</p><div className="scan-form"><label>İşletme<select value={clientId} onChange={e=>{setClientId(e.target.value);setUrl('')}}><option value="">Müşteri seçin</option>{clients.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Pilot müşterisinin e-postası<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Süre (gün)<input type="number" min="1" max="30" value={days} onChange={e=>setDays(e.target.value)}/></label><label>Gerekçe<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="button" disabled={busy||!clientId||!email||reason.trim().length<10} onClick={()=>submit('grant')}>Ücretsiz pilot aç</button>{selected?.pilot&&<button type="button" disabled={busy} onClick={()=>submit('revoke')}>Pilot erişimini kaldır</button>}</div>{msg&&<p role="status">{msg}</p>}{url&&<p><a href={url}>Pilot hesap oluşturma bağlantısını aç</a><small> Bu bağlantı müşteriye özeldir; genel paylaşmayın.</small></p>}</section>;
}
