'use client';
import {useCallback,useEffect,useState} from 'react';
import SourceReviewTransfer from './SourceReviewTransfer';
const stages={preflight:'Resmî site kontrolü',analysis:'Eski analiz kuyruğu / site kontrolü',contact:'İletişim hazırlığı'};
const statuses={pending:'Sırada',processing:'Çalışıyor',waiting:'Bekliyor',retry:'Tekrar denenecek','needs-review':'İnceleme gerekiyor'};
const reasons={'official-email-not-found':'Resmî sayfada yayımlanmış kurumsal e-posta bulunamadı.','official-page-unavailable':'Resmî sayfaya erişilemedi.','official-page-not-inspectable':'Sayfa kontrol edilemedi; güvenlik doğrulaması veya eksik HTML olabilir.','official-contact-recheck-failed':'Kayıtlı adres resmî sayfada yeniden doğrulanamadı.','ai-budget-unavailable-or-exhausted':'AI bütçesi dolu veya güncel bütçe bilgisi alınamıyor.','daily-analysis-limit':'Bugünün analiz denemesi sınırına ulaşıldı.','saved-analysis-required':'Geçerli sağlayıcı analizi gerekiyor.','official-evidence-or-analysis-required':'Resmî sayfa kanıtı veya kayıtlı analiz gerekiyor.','no-valid-provider-result':'Sağlayıcıdan geçerli analiz alınamadı.','worker-interrupted-three-times':'İş üç kez yarıda kaldı; inceleme gerekiyor.','preparation-stage-failed':'Hazırlık tamamlanamadı; otomatik tekrar denenecek.'};
function localTime(value){return new Date(value).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})}
export default function PreparationQueueStatus(){
 const [data,setData]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=useCallback(async()=>{const r=await fetch('/api/prospect-preparation-cycle',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Kuyruk alınamadı');setData(d)},[]);
 useEffect(()=>{let active=true;fetch('/api/prospect-preparation-cycle',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Kuyruk alınamadı');if(active)setData(d)}).catch(e=>{if(active)setMessage(e.message)});return()=>{active=false}},[]);
 async function refresh(){setBusy(true);setMessage('');try{await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function preflight(){setBusy(true);setMessage('');try{const r=await fetch('/api/prospect-preparation-cycle',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stage:'preflight'})}),d=await r.json();if(!r.ok)throw Error(d.error||'Kontrol tamamlanamadı');setMessage(`${d.processed} iş kontrol edildi; ${d.reused} kayıtlı analiz kullanıldı, ${d.waiting} iş bekliyor, ${d.errors.length} hata. E-posta gönderilmedi.`);await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 const count=(stage,status)=>data?.counts?.find(x=>x.stage===stage&&x.status===status)?.count||0;
 return <><SourceReviewTransfer/><section aria-label="Kalıcı hazırlık kuyruğu" className="panel"><h3>Kalıcı hazırlık kuyruğu</h3><p>Resmî site kontrolü ve iletişim hazırlığı ek AI çağrısı kullanmaz. İlk temas için AI analizi zorunlu değildir; doğrulanmış resmî sayfa bilgileri ayrı kaydedilir. Eski analiz kuyruğu da ücretli çağrı yapmadan site kontrolüne yönelir. AI ölçümü yalnız ayrı talep edilen ölçüm akışında yapılır; altyapı ve erişim kotaları geçerlidir. Süre dolunca kalan işler sonraki turda devam eder.</p>
 <button disabled={busy} onClick={refresh}>Kuyruk durumunu yenile</button>{' '}<button disabled={busy} onClick={preflight}>{busy?'Kontrol ediliyor…':'AI çağrısı olmadan site kontrolü başlat'}</button>
 {message&&<p role="status">{message}</p>}
 {!data?<p>Durum yükleniyor…</p>:<><p>Bugün {data.aiAttempts}/{data.dailyAnalysisLimit} analiz denemesi · Güncelleme: {localTime(data.asOf)}</p><small>Bir analiz denemesinde sağlayıcı yedekleri kullanılabilir; bu sayı API çağrısı veya kesin maliyet değildir. Saatlik çalışanlar kısa gruplar işler; uygunluk hemen tamamlanma sözü değildir.</small>
 <div style={{overflowX:'auto'}}><table><caption>Hazırlık aşamaları</caption><thead><tr><th scope="col">Aşama</th><th scope="col">Sırada</th><th scope="col">Çalışıyor</th><th scope="col">Bekleyen / tekrar</th><th scope="col">İnceleme</th><th scope="col">Biten</th></tr></thead><tbody>{Object.entries(stages).map(([key,label])=><tr key={key}><th scope="row">{label}</th><td>{count(key,'pending')}</td><td>{count(key,'processing')}</td><td>{count(key,'waiting')+count(key,'retry')}</td><td>{count(key,'needs-review')}</td><td>{count(key,'done')}</td></tr>)}</tbody></table></div>
 <details><summary>Bekleyen işlerin nedenleri ({data.recent.length} son kayıt)</summary>{data.recent.map(x=><article key={x.id}><h4>{x.name||'İşletme'} · {stages[x.stage]}</h4><p>{statuses[x.status]||x.status} · {x.attempts}/3 deneme</p><p>{reasons[x.reason]||(x.reason?'Hazırlık kaydı tamamlanamadı; inceleme gerekiyor.':'Sıranın gelmesi bekleniyor.')}</p>{['retry','waiting'].includes(x.status)&&<small>En erken tekrar: {localTime(x.availableAt)}</small>}</article>)}</details></>}
 </section></>;
}
