'use client';
import {useState} from 'react';
export default function SourceReviewTransfer(){
 const [offset,setOffset]=useState(0),[text,setText]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[batch,setBatch]=useState(null);
 async function exportBatch(){setBusy(true);try{const r=await fetch('/api/prospect-source-review?offset='+offset,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Dışa aktarılamadı');setBatch(d);const url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`aday-inceleme-${offset+1}.json`;a.click();URL.revokeObjectURL(url);setMessage(`${d.candidates.length} adayın araştırma kaydı indirildi. Dosyayı burada incelemek için sohbetle paylaşabilirsiniz.`)}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function importBatch(){setBusy(true);try{const r=await fetch('/api/prospect-source-review',{method:'POST',headers:{'content-type':'application/json'},body:text}),d=await r.json();if(!r.ok)throw Error(d.error||'Aktarılamadı');setMessage(`${d.results.filter(x=>x.status==='saved').length} kayıt doğrulandı; ${d.results.filter(x=>x.status==='not-verified').length} doğrulanamadı; ${d.results.filter(x=>x.status==='deferred').length} sonraki yüklemeye kaldı. AI çağrısı ve e-posta gönderimi yapılmadı.`)}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <section className="panel" aria-label="Kaynaklı inceleme aktarımı"><h3>Kaynaklı inceleme aktarımı</h3><p>Adayların mevcut araştırmasını 10 kayıtlık gruplarla indirin. Resmî kaynakta yeniden bulunan alıntılar ile bulgu, önerilen işlem ve belirsizlik ayrı kaydedilir. Bulgular inceleyici yorumudur; kaynak indekslerine bağlanır. Ek inceleme gereken adayın hazırlığı ve otomatik iletişimi bekler. AI skoru, satış olasılığı veya doğrulanmamış eksiklik aktarılmaz.</p>
 <button disabled={busy} onClick={exportBatch}>10 adayın araştırmasını indir</button>{' '}<button disabled={busy||!batch||batch.nextOffset===null} onClick={()=>{setOffset(batch.nextOffset);setBatch(null)}}>Sonraki 10 adaya geç</button><p>Grup başlangıcı: {offset+1}</p>{batch&&<details><summary>İndirilen araştırmayı ekranda göster</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(batch,null,2)}</pre></details>}{batch&&<details><summary>Kaydedilmiş inceleyici değerlendirmeleri</summary>{batch.candidates.filter(x=>x.sourceReview?.assessment).map(x=><article key={x.id}><h4>{x.name}</h4><p>{x.sourceReview.assessment.decision==='needs-review'?'Ek inceleme gerekli':'Hazırlığa uygun; iletişim kontrolleri devam eder'}</p><h5>Bulgu — inceleyici yorumu</h5><ul>{x.sourceReview.assessment.findings.map((f,i)=><li key={i}>{f.text}</li>)}</ul><h5>Önerilen işlem</h5><ul>{x.sourceReview.assessment.actions.map((a,i)=><li key={i}>{a.text}</li>)}</ul><h5>Belirsizlik</h5><ul>{x.sourceReview.assessment.uncertainties.map((u,i)=><li key={i}>{u}</li>)}</ul><details><summary>Dayanak kaynaklar</summary>{x.sourceReview.facts.map((f,i)=><p key={i}>[{i}] <a href={f.sourceUrl} target="_blank" rel="noreferrer">{f.sourceUrl}</a>: {f.excerpt}</p>)}</details></article>)}</details>}
 <details><summary>Doğrulanmış incelemeyi içeri aktar</summary><label htmlFor="source-review-json">Kaynaklı inceleme JSON’u</label><textarea id="source-review-json" rows={8} value={text} maxLength={50000} onChange={e=>setText(e.target.value)} placeholder={'{"reviews":[{"id":"aday UUID","facts":[{"sourceUrl":"https://resmi-site/","excerpt":"Sayfadan aynen alınmış açıklama"}]}]}'} /><button disabled={busy||!text.trim()} onClick={importBatch}>Kaynakları kontrol et ve kaydet</button></details>
 {message&&<p role="status">{message}</p>}</section>;
}
