"use client";
import {useEffect,useRef,useState} from "react";
import {readSystemHealthSnapshot} from '../lib/system-health-rules.js';
const fmt=v=>v&&Number.isFinite(Date.parse(v))?new Date(v).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'}):'—';
const labels={healthy:'GÜNCEL BAŞARI KAYDI',warning:'UYARI',delayed:'GECİKMİŞ',critical:'KRİTİK',quarantined:'KARANTİNA',unknown:'BİLİNMİYOR'};
export default function SystemHealthMap(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),request=useRef(0);
 async function load(){const version=++request.current;setLoading(true);try{const r=await fetch('/api/system-health-map',{cache:'no-store'}),value=await r.json();if(!r.ok)throw Error(value.error||'Sistem kontrol kayıtları alınamadı.');const next=readSystemHealthSnapshot(value);if(version===request.current){setData(next);setError('')}}catch(e){if(version===request.current){setData(null);setError(e.message)}}finally{if(version===request.current)setLoading(false)}}
 useEffect(()=>{load();const timer=setInterval(load,60000);return()=>{clearInterval(timer);request.current++}},[]);
 return <section className="panel" style={{marginBottom:18}}><div className="section-title"><div><h2>Sistem kontrol kayıtları</h2><p>Son başarı, gecikme ve karantina durumu. Her kayıt tek durum altında sayılır.</p></div><button onClick={load} disabled={loading}>{loading?'Kontrol ediliyor…':'Yenile'}</button></div>{error?<p role="alert">{error}</p>:!data?<p role="status">Kontrol kayıtları yükleniyor…</p>:<><p>{data.scope}</p><small>Son yükleme: {fmt(data.generatedAt)}{loading?' · Yeni kontrol bekleniyor; aşağıdaki kayıtlar önceki yüklemeye ait.':''}</small><dl style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(120px,1fr))',gap:8,marginTop:14}}>{Object.entries(labels).map(([key,label])=><div className="panel" key={key} style={{padding:10}}><dt>{label}</dt><dd style={{fontSize:22,fontWeight:900,margin:0}}>{data.counts[key]}</dd></div>)}</dl>{data.components.length?<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:8}}>{data.components.map(x=><article key={x.componentKey} className="panel" style={{padding:12,overflowWrap:'anywhere'}}><b>{x.componentKey}</b><p>{labels[x.state]}</p><small style={{display:'block'}}>Son görülen kontrol: {fmt(x.lastSeenAt)}</small><small style={{display:'block'}}>Son başarı: {fmt(x.lastSuccessAt)}{x.ageMinutes!==null?' · '+x.ageMinutes+' dk önce':''}</small><small style={{display:'block'}}>Son kayıt durumu: {x.lastStatus||'Bilinmiyor'}</small><small style={{display:'block'}}>Ardışık hata: {x.consecutiveFailures??'Bilinmiyor'} · Beklenen aralık: {Number(x.expectedIntervalMinutes)>0?x.expectedIntervalMinutes+' dk':'Bilinmiyor'}</small><small style={{display:'block'}}>Kurtarma denemesi: {x.recoveryAttempts??'Bilinmiyor'} · Son: {fmt(x.lastRecoveryAt)}</small>{x.quarantineUntil&&<p>Karantina bitişi: {fmt(x.quarantineUntil)}</p>}{x.detail&&<p>{x.detail}</p>}</article>)}</div>:<p>Henüz sistem kontrol kaydı yok; bu durum ajanların çalıştığını doğrulamaz.</p>}</>}</section>;
}
