"use client";
import Link from "next/link";
import BottomNavigation from "./BottomNavigation";
import LogoutButton from "./LogoutButton";
import {LanguageSwitcher,useLanguage} from "./LanguageProvider";
export const items=[["/admin","⌂","home"],["/musteriler","♙","clients"],["/isletme-hesabi","◎","business"],["/taramalar","⌕","scans"],["/raporlar","▥","reports"],["/ajanlar","⌘","agents"],["/ayarlar","⚙","settings"]];
const desktopItems=[["/admin","⌂","Genel görünüm"],["/lead-finder","⌕","Müşteri bulma"],["/musteriler","♙","Müşteriler"],["/ajanlar","⌘","Ajan merkezi"],["/taramalar","◎","Taramalar"],["/raporlar","▥","Raporlar"],["/lansman-kontrol","✓","Lansman kontrolü"],["/ayarlar","⚙","Ayarlar"]];
export function Nav(){return <BottomNavigation/>}
export function Shell({title,subtitle,children}){const {t}=useLanguage();return <main className="admin-shell"><aside className="admin-shell-side" aria-label="Yönetici masaüstü menüsü"><Link href="/admin" className="admin-shell-logo"><span>◈</span><div><strong>AI Visibility</strong><small>EXECUTIVE CONTROL CENTER</small></div></Link><div className="admin-shell-live"><i/> {t("liveProtected")}</div><nav>{desktopItems.map(([href,icon,label])=><Link href={href} key={href}><b>{icon}</b><span>{label}</span></Link>)}</nav><div className="admin-shell-note"><strong>Kanıta dayalı operasyon</strong><span>Gerçek müşteri, tarama ve ajan verileri mevcut yetkili oturumdan yüklenir.</span></div></aside><section className="admin-shell-main"><header className="top admin-shell-top"><Link href="/admin" className="brand"><span className="logo">A</span><div><strong>AI VISIBILITY</strong><small>{t("adminPanel")}</small></div></Link><div className="admin-shell-actions"><LanguageSwitcher/><span className="badge">{t("liveProtected")}</span><LogoutButton compact/></div></header>{title&&<section className="page-head admin-page-head"><div><span className="admin-page-kicker">DIGITAL VISIBILITY INTELLIGENCE</span><h1>{title}</h1><p>{subtitle}</p></div><div className="admin-page-trust"><span>● Yetkili oturum</span><span>Kanıt bağlantılı çalışma</span></div></section>}<div className="admin-shell-content">{children}</div></section><Nav/></main>}
