import {getDatabaseUrl} from "./db";
function clean(v,n=300){return String(v||"").trim().slice(0,n)}
function norm(v){return clean(v,400).toLowerCase().replace(/^https?:\/\//,"").replace(/^www\./,"").replace(/\/$/,"")}
async function db(fn){const raw=getDatabaseUrl();if(!raw)throw new Error("database-not-configured");const {Pool}=await import("pg");const pool=new Pool({connectionString:raw});try{await pool.query(`CREATE TABLE IF NOT EXISTS discovered_leads(id UUID PRIMARY KEY,business_name TEXT NOT NULL,website TEXT NOT NULL DEFAULT '',country TEXT NOT NULL DEFAULT '',city TEXT NOT NULL DEFAULT '',sector TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL DEFAULT '',email TEXT NOT NULL DEFAULT '',source TEXT NOT NULL DEFAULT 'lead-finder',source_url TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'discovered',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await pool.query("ALTER TABLE discovered_leads ADD COLUMN IF NOT EXISTS qualification_score INTEGER NOT NULL DEFAULT 0");await pool.query("ALTER TABLE discovered_leads ADD COLUMN IF NOT EXISTS qualification_level TEXT NOT NULL DEFAULT 'unrated'");await pool.query("ALTER TABLE discovered_leads ADD COLUMN IF NOT EXISTS qualification_reason TEXT NOT NULL DEFAULT ''");await pool.query("ALTER TABLE discovered_leads ADD COLUMN IF NOT EXISTS contact_channel TEXT NOT NULL DEFAULT ''");await pool.query("ALTER TABLE discovered_leads ADD COLUMN IF NOT EXISTS contact_value TEXT NOT NULL DEFAULT ''");await pool.query("ALTER TABLE discovered_leads ADD COLUMN IF NOT EXISTS contact_source TEXT NOT NULL DEFAULT ''");await pool.query("ALTER TABLE discovered_leads ADD COLUMN IF NOT EXISTS contact_verified BOOLEAN NOT NULL DEFAULT FALSE");await pool.query("ALTER TABLE discovered_leads ADD COLUMN IF NOT EXISTS contact_reason TEXT NOT NULL DEFAULT ''");return await fn(pool)}finally{await pool.end()}}
export async function saveDiscovered(items=[]){return db(async p=>{const out=[];for(const x of items.slice(0,50)){const name=clean(x.businessName,180);if(name.length<2)continue;const website=clean(x.website,300),country=clean(x.country,100),city=clean(x.city,100),sector=clean(x.sector,140);const dup=await p.query(`SELECT * FROM discovered_leads WHERE (website<>'' AND lower(regexp_replace(website,'^https?://(www\\.)?','','i'))=$1) OR (lower(business_name)=$2 AND lower(city)=$3) LIMIT 1`,[norm(website),name.toLowerCase(),city.toLowerCase()]);if(dup.rows[0]){out.push({...dup.rows[0],duplicate:true});continue}const id=crypto.randomUUID();const r=await p.query(`INSERT INTO discovered_leads(id,business_name,website,country,city,sector,phone,email,source_url) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,business_name AS "businessName",website,country,city,sector,phone,email,source_url AS "sourceUrl",status,created_at AS "createdAt"`,[id,name,website,country,city,sector,clean(x.phone,80),clean(x.email,180).toLowerCase(),clean(x.sourceUrl,500)]);out.push(r.rows[0])}return out})}
const HIGH_VALUE_MARKETS=new Set(["united states","united kingdom","germany","france","netherlands","canada","united arab emirates","saudi arabia","singapore","australia","japan","austria","switzerland","hong kong"]);
const STRONG_FIT=["sağlık","klinik","diş","otel","turizm","emlak","gayrimenkul","otomotiv","güzellik","e-ticaret","hukuk","eğitim","yazılım","teknoloji","fitness","restoran"];
export async function qualifyDiscovered(){return db(async p=>{
 const rows=(await p.query("SELECT * FROM discovered_leads")).rows;
 for(const x of rows){
  let score=10,reasons=[];
  const country=String(x.country||"").toLowerCase(),sector=String(x.sector||"").toLowerCase();
  if(x.website){score+=20;reasons.push("doğrulanabilir web var")}
  if(x.source_url){score+=10;reasons.push("kamusal kaynak var")}
  if(x.email){score+=20;reasons.push("doğrudan e-posta kanalı")}
  else if(x.phone){score+=10;reasons.push("telefon kanalı")}
  if(HIGH_VALUE_MARKETS.has(country)){score+=15;reasons.push("yüksek ticari değerli pazar")}
  else if(country==="türkiye"||country==="turkey"){score+=10;reasons.push("öncelikli Türkiye pazarı")}
  if(STRONG_FIT.some(s=>sector.includes(s))){score+=15;reasons.push("çözüm satılabilirliği güçlü sektör")}
  if(x.website&&x.source_url){score+=5;reasons.push("kimlik doğrulama güçlü")}
  if(x.email&&x.website){score+=5;reasons.push("satışa ulaşılabilir")}
  score=Math.max(0,Math.min(100,score));
  const level=score>=75?"hot":score>=50?"warm":"low";
  await p.query("UPDATE discovered_leads SET qualification_score=$2,qualification_level=$3,qualification_reason=$4,status=$5,updated_at=NOW() WHERE id=$1",[x.id,score,level,reasons.join(" · ")||"sınırlı doğrulanabilir satış sinyali",level==="hot"?"qualified-hot":level==="warm"?"qualified-warm":"qualified-low"]);
 }
 return rows.length
})}
export async function listDiscovered(limit=100){return db(async p=>(await p.query(`SELECT id,business_name AS "businessName",website,country,city,sector,phone,email,source_url AS "sourceUrl",status,qualification_score AS "qualificationScore",qualification_level AS "qualificationLevel",qualification_reason AS "qualificationReason",contact_channel AS "contactChannel",contact_value AS "contactValue",contact_source AS "contactSource",contact_verified AS "contactVerified",contact_reason AS "contactReason",created_at AS "createdAt" FROM discovered_leads ORDER BY qualification_score DESC,created_at DESC LIMIT $1`,[Math.min(200,Math.max(1,Number(limit)||100))])).rows)}

export async function prepareContactQueue(limit=50){return db(async p=>{const rows=(await p.query("SELECT * FROM discovered_leads WHERE qualification_level IN ('hot','warm') ORDER BY qualification_score DESC,created_at DESC LIMIT $1",[Math.max(1,Math.min(Number(limit)||50,100))])).rows;let prepared=0;for(const x of rows){let channel='',value='',source=x.source_url||x.website||'',verified=false,reason='';if(x.email&&/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(x.email)){channel='email';value=x.email;verified=Boolean(x.source_url||x.website);reason='Kamusal işletme kaydında e-posta mevcut'}else if(x.phone){channel='phone';value=x.phone;verified=Boolean(x.source_url);reason='Kamusal işletme kaydında telefon mevcut'}else if(x.website){channel='website';value=x.website;verified=Boolean(x.source_url);reason='Doğrulanabilir web sitesi üzerinden iletişim araştırılmalı'}else{reason='Doğrulanmış iletişim kanalı bulunamadı'}const status=channel?(verified?'contact-ready':'contact-review'):'contact-missing';await p.query('UPDATE discovered_leads SET contact_channel=$2,contact_value=$3,contact_source=$4,contact_verified=$5,contact_reason=$6,status=$7,updated_at=NOW() WHERE id=$1',[x.id,channel,value,source,verified,reason,status]);if(channel)prepared++}return {checked:rows.length,prepared}})}
