export function permissionEnquiry(x,follow=false){
 const tr=/^(Türkiye|Turkey|TR)$/i.test(String(x.country||'')),name=String(x.name||'').slice(0,180);
 return tr?(follow?`Merhaba ${name} ekibi,\n\nAI Visibility Works olarak AI görünürlüğü hakkında gönderdiğimiz mesajı bir kez hatırlatmak istedik. İşletmenize yönelik kısa bir değerlendirme paylaşmamızı ister misiniz?\n\nİlgilenmiyorsanız bu e-postaya yazmanız yeterli; tekrar iletişim kurmayacağız.\n\nAI Visibility Works`:`Merhaba ${name} ekibi,\n\nAI Visibility Works olarak işletmelerin yapay zekâ aramalarındaki görünürlüğünü değerlendiren analiz ve iyileştirme hizmetleri sunuyoruz. İşletmeniz için kısa bir değerlendirme paylaşmamızı ister misiniz?\n\nBu mesaj tamamlanmış bir analiz veya sonuç garantisi içermez. İlgilenmiyorsanız yanıtlayarak belirtmeniz yeterli; tekrar iletişim kurmayacağız.\n\nAI Visibility Works`):(follow?`Hello ${name} team,\n\nA brief follow-up to our AI Visibility Works enquiry: would you like us to share a short assessment of your business's discoverability in AI search?\n\nIf this is not relevant, reply to let us know and we will stop contacting you.\n\nAI Visibility Works`:`Hello ${name} team,\n\nAI Visibility Works offers analysis and improvement services for how businesses appear in AI search. Would you be interested in receiving a short assessment for your business?\n\nThis enquiry does not claim a completed audit or guaranteed results. If this is not relevant, reply to let us know and we will stop contacting you.\n\nAI Visibility Works`);
}
// Exact reviewed enquiries keep stale generated drafts and edited unsupported claims out of first contact.
export function safeFirstContact(x){
 const draft=String(x.outreachDraft||'').trim();
 return [permissionEnquiry(x),permissionEnquiry(x,true)].some(v=>v.trim()===draft);
}
